### ISSUE TITLE
多个规则时被覆盖

### ISSUE THREAD

**Issue by 9tail123** [gh0stkey/HaE#10]
写个测试文件
![360桌面截图20201130012145](https://user-images.githubusercontent.com/35592183/100592432-f409a000-32ab-11eb-9366-e38e1842ddc6.jpg)
规则匹配shiro
![360桌面截图20201130012159](https://user-images.githubusercontent.com/35592183/100592516-0b488d80-32ac-11eb-9d55-d615eae10642.jpg)
此时可以正常匹配到
![360桌面截图20201130012212](https://user-images.githubusercontent.com/35592183/100592558-1e5b5d80-32ac-11eb-897e-fef239585c30.jpg)
再加一条规则
![360桌面截图20201130012239](https://user-images.githubusercontent.com/35592183/100592602-2e733d00-32ac-11eb-9215-c01580a155a6.jpg)
再次请求匹配失败
![360桌面截图20201130012312](https://user-images.githubusercontent.com/35592183/100592657-4054e000-32ac-11eb-8b9b-c80c5765b1a0.jpg)
点击Reload之前
![360桌面截图20201130013041](https://user-images.githubusercontent.com/35592183/100592725-58c4fa80-32ac-11eb-8005-b7b9e87aec14.jpg)
点击Reload之后
![360桌面截图20201130013051](https://user-images.githubusercontent.com/35592183/100592795-709c7e80-32ac-11eb-8e41-03339c969d15.jpg)
可以很清楚看到shiro匹配规则被覆盖，并没有共同生效，导致多个规则匹配时无法生效

**Comment by gh0stkey** [comment]
你好，这个是因为全局是以Name作为字段去增加、删除、修改的，所以不能出现Name字段一样的。

**Comment by 9tail123** [comment]
好的，感谢，测试了一下，的确是这里问题。:+1:

**Comment by 9tail123** [comment]
另外问一句，burp是否提供有任务栏图标闪动或其他更强一些的提醒的api? 如果有的话我感觉加上应该会有不错的效果，毕竟有些时候只是挂着burp在被动检测，没有主动去翻的话会容易遗漏一些漏洞。

**Comment by gh0stkey** [comment]
可以考虑下是否需要，感谢建议！
