### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by Wnltc** [gh0stkey/HaE#100]
1.面板搜索时，无法搜索ip:port的形式
2.获取在线规则时，可否考虑与现有规则合并而非覆盖，或者添加选项由用户决定覆盖已有规则还是与现有规则合并

**Comment by gh0stkey** [comment]
非常感谢你的建议：
1. 关于Databoard面板搜索的问题，我们打算对照着BurpSuite的Target面板进行重构；
2. 关于在线规则的更新覆盖问题，我们会在新版本中进行改进，感谢！
