### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by JDXN** [gh0stkey/HaE#102]
1、建议增加上下文查看配置【配置后，会自动提取命中规则处的上下文，具体多少由自己定义，有总开关可以显示或隐藏所有的上下文，也对单一命中规则的后面加上显示或隐藏上下文按钮（有些命中内容需要结合上下文参考，但如果默认就是的话，内容会显得很多很杂，所以建议显示面板的每条命中内容后面增加显示上下文按钮）】

2、建议增加对单条规则可以设置命中哪些文件【比如有些规则不想命中js，因为误报很多；有些规则只适用于后缀为xx的文件】

3、建议规则能够进行自定义的与或非多条件组合查询，比如按+号可以添加一行条件

4、建议在查询结果面板增加关键字搜索功能【最好能使用正则匹配，且能进行多条件组合查询】，以便快速筛选自己想要的内容

5、建议结果面板增加排序功能，可以按字符顺序排序【这样结果就会更清晰，方便分析】

6、类似log++那样，增加从proxyhistory导入并分析的功能（或者加入到扫描器中，点击扫描后自动进行分析）【重新打开历史项目后，方便导入并快速查看hae结果，不用再去网页点击；也方便更新规则后，快速重新分析处理，查看新结果】

望采纳，感谢!~

**Comment by gh0stkey** [comment]
你一定是一个好的产品经理，很多优化建议都值得我们去采纳，感谢！

**Comment by gh0stkey** [comment]
#105 #104
