### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by AliceOops** [gh0stkey/HaE#107]
能不能增加一个规则的优先级
![5D4$ER2X6_GEN W33OU HN7](https://user-images.githubusercontent.com/90129264/224453688-d698679c-2d4d-4af2-8e6d-60a9e691f7f1.png)
我添加了2个规则，2个都匹配到了，但是显示的永远都是红色的那一个

**Comment by gh0stkey** [comment]
那你看Comment不就可以了，颜色高亮是有升级算法的，肯定优先是最高的那个颜色。
