### ISSUE TITLE
BUG HaE 2.4.6规则匹配爬取加载异常卡顿缓慢

### ISSUE THREAD

**Issue by ghost** [gh0stkey/HaE#110]
burp2023.3 安装HaE 2.4.6版时公规则文件进行抓包，浏览器里响应会异常缓慢，history看历史数据包异常卡顿缓慢。
换回HaE 2.4.5，更新最新的公共规则文件配置，无以上问题。

**Comment by gh0stkey** [comment]
这个问题我暂时没有遇到，可以发一下你的测试站到我的邮箱：admin[#]gh0st.cn
