### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by yuzhe-Mortal** [gh0stkey/HaE#112]
师傅你好，我自己通过源码编译发现编译不了，报错：
java.lang.Exception: Extension class is not a recognized type	at burp._f8.E(Unknown Source)	at burp._f8.v(Unknown Source)	at burp.lvh.d(Unknown Source)	at burp.xqg.F(Unknown Source)	at burp.ncn.lambda$panelLoaded$0(Unknown Source)	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)	at java.base/java.lang.Thread.run(Thread.java:833)
而且大小也不对，只有61kb不知道是哪出了问题

**Comment by yuzhe-Mortal** [comment]
我用maven弄好了，谢谢师傅

**Comment by gh0stkey** [comment]
可能是Gradle配置问题吧，弄好了就行～
