### ISSUE TITLE
添加规则

### ISSUE THREAD

**Issue by j4vaovo** [gh0stkey/HaE#114]
<img width="342" alt="233" src="https://user-images.githubusercontent.com/128683738/232269887-f2474621-4c93-4e4e-bd76-e4d7cd078635.png">

````
((?i)(Paho\.MQTT\.Client|.mqtt\.aliyuncs\.com|mqtt\.js|mqtt\.class\.js|paho-mqtt-min\.js))
````

**Comment by gh0stkey** [comment]
麻烦说明一下实际用途

**Comment by j4vaovo** [comment]
https://bacde.me/post/mqtt-security-part-two/
