### ISSUE TITLE
加载大的数据包卡死

### ISSUE THREAD

**Issue by seventeenman** [gh0stkey/HaE#115]
![image](https://user-images.githubusercontent.com/84114371/234522980-53a66f0a-789f-4f4d-9772-e62fdfa855ce.png)
如图大数据包burpsuite就会卡死，该工具有在几十条规则的条件下，在实际项目中进行落地测试吗

**Comment by gh0stkey** [comment]
...没落地测试，我开发出来给谁用的，卡死的问题除了HaE以外，还有你自己正则写的问题，已经尽量去优化了，本身Java的GUI界面就会加载数据卡顿，实在不行，要不您提个PR？

**Comment by seventeenman** [comment]
好的，应该是我正则或者电脑配置有问题
