### ISSUE TITLE
异常显示 null 的 bug

### ISSUE THREAD

**Issue by ba1ma0** [gh0stkey/HaE#117]
Hi key  师傅你好:
我在使用 HaE 的时候,不知道为什么总是会显示一个 null,而且我让旁边的同事试了一下, 也存在相同的问题,下面是我遇到问题的截图,以及我自己的环境信息
<img width="1792" alt="截屏2023-05-24 16 34 58" src="https://github.com/gh0stkey/HaE/assets/32502627/e5776647-f497-4b6a-aba0-5eea877082bc">
<img width="1126" alt="截屏2023-05-24 16 41 24" src="https://github.com/gh0stkey/HaE/assets/32502627/38799a6d-d74c-49a8-a0ab-21ca4b210f8e">
<img width="884" alt="截屏2023-05-24 16 42 39" src="https://github.com/gh0stkey/HaE/assets/32502627/180d1532-4f01-47ae-bd3d-26241b25e1d1">
-7e834f4a2291">

OS             : macOS 13.0.1
burp          : v2022.8
HaE           : 我测试了 v2.4.6,v2.4.5,2.4.4(直接从 BApp 下载)
Rules         : https://raw.githubusercontent.com/gh0stkey/HaE/gh-pages/Config.yml
测试站点   :https://weixin.qq.com

**Comment by gh0stkey** [comment]
与Burp版本有关，可以升级下Burp
