### ISSUE TITLE
[建议]关于卡顿的一个解决方法

### ISSUE THREAD

**Issue by No-Github** [gh0stkey/HaE#118]
这个方法在我实际使用时有一定改善,不确定是不是心里作用，建议各位师傅自己实际体验试试

主要就是修改运行jar包时的参数

1. 加内存
```
-Xmx4048m
```

2. 服务器模式
```
-server
```

<img width="724" alt="image" src="https://github.com/gh0stkey/HaE/assets/18167071/3a725dc3-3f95-4eae-b0ba-e0f424ad99d6">

实际使用加载这类大js文件,也基本正常,卡顿不是很明显,更不会卡死

**Comment by gh0stkey** [comment]
我的启动参数如下，基本上没卡死过，正则消耗内存是很正常的，再加上超大文件内容，在任何GUI中都没法得到好的支持，毕竟不是专业的文本编辑器：
```
-Xmx10G
-XX:MaxRAMPercentage=50
```

**Comment by gh0stkey** [comment]
感谢提建议，么么么～
