### ISSUE TITLE
2022年以上高版本java（java17）的burpsuite完全无法使用啊。

### ISSUE THREAD

**Issue by xslzlccc** [gh0stkey/HaE#122]
1、在线升级功能永远只能显示【Please check your network！】
![image](https://github.com/gh0stkey/HaE/assets/50007642/98f4432a-fbf8-4e85-a1d3-947325553756)
更糟糕的是https://raw.githubusercontent.com/gh0stkey/HaE/gh-pages/Config.yml这个链接过期了。。。。

**Comment by gh0stkey** [comment]
哥们，咱要不翻个墙在访问下呀：
<img width="909" alt="image" src="https://github.com/gh0stkey/HaE/assets/24655118/146e46f3-9e78-4743-b32c-e6d5a2adbe3f">

**Comment by xslzlccc** [comment]
> 哥们，咱要不翻个墙在访问下呀： <img alt="image" width="909" src="https://user-images.githubusercontent.com/24655118/253496265-146e46f3-9e78-4743-b32c-e6d5a2adbe3f.png">

艹，没道理的，我忘了开吗，我的我的，问题关了吧 有点呆
