### ISSUE TITLE
优化建议：能否增加一个右键菜单“scan by HaE”,主动触发扫描

### ISSUE THREAD

**Issue by fishso** [gh0stkey/HaE#123]
场景：
1、新增加了一条规则，针对http histroy中的记录进行主动触发扫描
2、去掉了配置中的几条规则，针对http histroy中的记录进行主动触发扫描

目前是自动被动扫描，没有主动触发方式，当规则变化后，想重新执行敏感信息检测，但目前无法支持

**Comment by gh0stkey** [comment]
不错的建议，有个更快速的方法，你把原请求访问Repeater重放一下就行了。
