### ISSUE TITLE
关于优化中国居民身份证的正则匹配规则误报率的建议

### ISSUE THREAD

**Issue by kenyon-wong** [gh0stkey/HaE#124]
关于中国居民身份证号的正则匹配规则，目前存在着相当高的误报率。虽然通过正则表达式的方式难以完全避免误报问题，但是目前的规则会匹配到一些年份大于当前标准年份的记录，这种匹配的结果情况令人不太满意。为了解决这一问题，我有两种优化建议供参考：

1. **引入实时时间查询API**：考虑引入一个时间查询API，最好能够直接获取系统当前时间，并将其作为变量嵌入到正则表达式中。这样，可以使正则表达式中可以以当前标准年作为一项条件来进行匹配，这样可以减少关于中国居民身份证号的正则匹配规则的误报率，同时也可以使正则表达式的编写更加灵活；
2. **增加用户输入标签栏**：在插件中增加一个用户输入标签栏。通过提示用户输入一些常见信息（如当前年份等）作为变量，虽然这种方式可能对用户来说稍显繁琐，但是，用户的这些输入可以用于修正和优化正则表达式，使其更加准确；并且后期可以根据社区的反馈，逐步增加更多信息项以提高其他正则表达式的精度。

**Comment by gh0stkey** [comment]
你的第一个建议实际上没法解决这一问题，在我另外一个项目中有关于身份证的校验逻辑：https://github.com/gh0stkey/RGPerson#genidcard，早期版本的HaE是支持的，但由于后期更偏向于一个框架，去除了该单一性功能，目前HaE正在寻求新的发展和改变，感谢您的关注和建议，谢谢！
