### ISSUE TITLE
配置文件优化

### ISSUE THREAD

**Issue by theLSA** [gh0stkey/HaE#13]
1. README_zh.md中如下描述有误：
"初始化的配置文件会放在与BurpSuite Jar包同级目录下"
应为：初始化的配置文件会放在启动BurpSuite Jar包的当前目录下。
//如：在/home/test/目录下用绝对路径启动/home/test/tools/burpsuite.jar，hae的配置文件在/home/test/目录下。

2. 个人认为hae的配置文件不需要分为config.json和init.hae，直接在hae插件目录使用config.json，添加删除规则直接操作config.json即可。

**Comment by gh0stkey** [comment]
init.hae 是为了便于下个版本的其他配置项，故暂不考虑删除，关于描述部分后续会更新，感谢
