### ISSUE TITLE
Databoard页面汇总不全

### ISSUE THREAD

**Issue by AmiaaaZ** [gh0stkey/HaE#131]
2.4.8版本，Databoard记录远少于HTTP history页面显示的敏感信息数量，比如上图Linkfinder数量最少大于1，但下图只显示1条，而且内容是“http://nginx.org/r/error_log”

![HTTP history页面显示数量](https://amiz-1307622586.cos.ap-chongqing.myqcloud.com/images/Snipaste_2023-10-11_14-22-19.jpg)

![Databoard页面显示数量](https://amiz-1307622586.cos.ap-chongqing.myqcloud.com/images/image-20231011143113648.png)

**Comment by AmiaaaZ** [comment]
重新加载后解决

**Comment by gh0stkey** [comment]
2.5版本解决了很多BUG，近几天会发布，感谢反馈。
