### ISSUE TITLE
[特性] 支持相对路径的配置文件

### ISSUE THREAD

**Issue by peter5he1by** [gh0stkey/HaE#132]
能否按优先级读取配置文件，如：

- %USERPROFILE%\\.config\\HaE
- 插件jar包所在目录\\.config\\HaE

以支持便携的burpsuite部署。(因为有的渗透或者红队要在vdi部署环境）

**Comment by gh0stkey** [comment]
感谢建议，下一版本中加入。

**Comment by gh0stkey** [comment]
再次感谢建议，目前2.5.2版本已经加入该功能：https://github.com/gh0stkey/HaE/releases/tag/2.5.2
