### ISSUE TITLE
多次点击，加载信息无法重置

### ISSUE THREAD

**Issue by atk-admin** [gh0stkey/HaE#135]
![image](https://github.com/gh0stkey/HaE/assets/107470327/1fd64cf4-d0eb-42d0-b663-888b84fd8155)

**Comment by gh0stkey** [comment]
HaE是啥版本，BurpSuite是啥版本，多次点击是什么场景下，可以具体说一下哈。

**Comment by atk-admin** [comment]
hae-最新版，bp-2023.10 ，场景重复点击相同的url连接markinfo框中的标签信息会重复显示类似（用户名1，用户名1，用户名1）
![image](https://github.com/gh0stkey/HaE/assets/107470327/ab496efc-6bea-417f-b963-ff80d7f4b164)

**Comment by atk-admin** [comment]
![image](https://github.com/gh0stkey/HaE/assets/107470327/37570782-6f74-40e1-9ef5-fbbf68cff35e)

**Comment by gh0stkey** [comment]
我实际测试没遇到这个问题，逻辑上也不会出现这个问题，可以尝试升级到最新版本的Burp试一下。

**Comment by gh0stkey** [comment]
另外可能由于你使用的是中文汉化的BurpSuite，会存在这个问题，可以切换一下英文版本。
