### ISSUE TITLE
2.5.5的默认rule规则链接访问有问题

### ISSUE THREAD

**Issue by xj90512** [gh0stkey/HaE#137]
GET /gh/gh0stkey/HaE@gh-pages/Rules.yml HTTP/1.1
Host: cdn.jsdelivr.net
![image](https://github.com/gh0stkey/HaE/assets/5670103/b1acf895-0979-4820-b23b-d286fa609ed8)

**Comment by xj90512** [comment]
应该是我本地环境网络问题，是不是可以考虑onlineupdate可以配置在线更新链接，方便维护

**Comment by xj90512** [comment]
重复问题，关闭

**Comment by gh0stkey** [comment]
其实你可以在Github项目分支直接下载。
