### ISSUE TITLE
关于2.5.6版本HAE输出结果的问题

### ISSUE THREAD

**Issue by zornsoon** [gh0stkey/HaE#143]
您好，key个，我发现2.5.6版本HAE对输出的结果有问题

这里我返回值只有Response_URL的，但是点进去，出现的上面匹配到的内容
![image](https://github.com/gh0stkey/HaE/assets/61613298/f82dc5cc-06a8-4d09-b9df-987d9ac9ab8c)

还有这个输出结果，我点击Email的，出现的结果是三个内容，之前的版本是只显示Email出现的JS文件
![image](https://github.com/gh0stkey/HaE/assets/61613298/f23c484c-3af9-4c5c-9c48-098c076c688f)

**Comment by gh0stkey** [comment]
该问题确实存在，由于新增了表格字段忘记更新取值索引了，下个版本修复，感谢！

**Comment by gh0stkey** [comment]
最新版本（2.5.7）已修复该问题：https://github.com/gh0stkey/HaE/releases/tag/2.5.7
