### ISSUE TITLE
config.yml访问404，翻墙了，是节点有问题吗？

### ISSUE THREAD

**Issue by Tra5h-A** [gh0stkey/HaE#144]
<img width="975" alt="image" src="https://github.com/gh0stkey/HaE/assets/48111325/38dc9d8a-1ea0-4501-8e8a-ed7e5fd4d222">
但是访问rules.yml就可以正常访问

**Comment by gh0stkey** [comment]
Config.yml不是在线的配置呢，HaE本地会直接生成的，谢谢。
