### ISSUE TITLE
解决网络问题的一些建议

### ISSUE THREAD

**Issue by winezer0** [gh0stkey/HaE#145]
强烈 建议内部预置最新的config文件，避免没有网络无法正常加载和使用程序。
后续用户手动点击按钮进行配置文件更新

这个网络问题已经迭代了好多个版本了，希望大佬能够关注到【 内网、无代理场景下的 】使用问题。

**Comment by winezer0** [comment]
希望在配置文件内添加一列update url ，用于指定更新rule.yml文件的地址。

**Comment by winezer0** [comment]
> 强烈 建议内部预置最新的config文件，避免没有网络无法正常加载和使用程序。 后续用户手动点击按钮进行配置文件更新

内网问题可通过 【便携功能】进行解决。
选择将配置文件存放在HaE Jar包的同级目录下的/.config/HaE/中，以便于离线携带。

感谢 gh0stkey 师傅的解答

**Comment by gh0stkey** [comment]
自定义URL进行规则更新，已加入TODO。感谢建议。
