### ISSUE TITLE
自定义规则出现问题

### ISSUE THREAD

**Issue by DatangST** [gh0stkey/HaE#146]
你好，key哥，自己写了一个规则。测试没问题。但是放入插件中，burp一直检测不到这个规则
![image](https://github.com/gh0stkey/HaE/assets/52750566/7e0f0fe0-6fe2-4362-bc0a-b22ac16a877f)
![image](https://github.com/gh0stkey/HaE/assets/52750566/cabe7f15-2120-4433-bdbb-8f1f19bde54c)
并不会展示
![image](https://github.com/gh0stkey/HaE/assets/52750566/6dccd1ba-1afb-447a-8e78-3f3e7fe4a513)

**Comment by gh0stkey** [comment]
> 注: 要想灵活的使用HaE，你需要掌握正则表达式阅读、编写、修改能力；由于Java正则表达式的库并没有Python的优雅或方便，所以HaE要求使用者必须用()将所需提取的表达式内容包含；例如你要匹配一个Shiro应用的响应报文，正常匹配规则为rememberMe=delete，如果你要提取这段内容的话就需要变成(rememberMe=delete)。
