### ISSUE TITLE
关于Burpsuite长时间加载HAE，Databoard界面使用不了问题

### ISSUE THREAD

**Issue by zornsoon** [gh0stkey/HaE#148]
hello，key哥，是这样，当我使用Burpsuite长时间使用HAE后，在使用Dashboard界面，会一直卡

这个输入匹配的语法，根本输入不了
![image](https://github.com/gh0stkey/HaE/assets/61613298/2c60504e-d706-457d-ac5f-59ad23997e29)

中间字符出现空白
![image](https://github.com/gh0stkey/HaE/assets/61613298/9e675b74-0817-446a-837c-d683016b47b6)

**Comment by gh0stkey** [comment]
这个问题确实出现了很久了，正在排查。

**Comment by gh0stkey** [comment]
已发布修复版本，烦请师傅下载最新版本，如有问题欢迎继续反馈：https://github.com/gh0stkey/HaE/releases/tag/2.5.8
