### ISSUE TITLE
最新版有bug

### ISSUE THREAD

**Issue by JDXN** [gh0stkey/HaE#149]
最新版有bug：
自定义的规则，双击无法定位数据包
![image](https://github.com/gh0stkey/HaE/assets/66476205/60a093eb-e872-41fb-be44-2d104f521cb4)

**Comment by gh0stkey** [comment]
麻烦补充下以下内容：
```
HaE版本：
BurpSuite版本：
操作系统版本：
```

**Comment by gh0stkey** [comment]
https://github.com/gh0stkey/HaE/releases/tag/2.5.7 确定是2.5.7版本么？

**Comment by JDXN** [comment]
经测试，从hae 2.5.6版开始就出现问题了，首先是dashboard面板的请求记录的颜色标识没有了，其次关于post数据包那些，双击命中的数据后，无法定位请求记录，请求记录栏为空白；【自定义的正则为：([^&,]*[=:][^&,]*)】用于匹配request中的等号和冒号的键值对
burp版本是：v2022.5.1，经测试，最新版bp也存在此问题；
操作系统：win10
![image](https://github.com/gh0stkey/HaE/assets/66476205/8813bb5f-c7e2-4fd9-909e-35343ee53681)

![image](https://github.com/gh0stkey/HaE/assets/66476205/e90bdf01-4649-40db-9371-a5ea94e886ea)

**Comment by gh0stkey** [comment]
请问您现在是什么HaE版本，2.5.6版本确实有这个问题，但是已经修复了。

**Comment by JDXN** [comment]
2.5.7
![image](https://github.com/gh0stkey/HaE/assets/66476205/c98490af-8852-4c54-8b9b-4a8f49321c91)

2.5.7的bug甚至更严重了
连一般的请求记录都看不到，不管是自定义规则还是默认规则都是
burp版本是专业版v2022.5.1

**Comment by gh0stkey** [comment]
你自定义了哪些正则，麻烦您使用反引号的方式将正则列出来，我来看下，有可能是您定义的正则不规范导致的呢，也可以采取控制变量法来判断，您可以先用官方的规则库看看有没有问题呢，谢谢配合。

**Comment by JDXN** [comment]
自定义的规则是：【自定义的正则为：([^&,][=:][^&,])】用于匹配request中的等号和冒号的键值对
官方规则的linkFinder也是，双击命中的记录，看不到请求记录

**Comment by gh0stkey** [comment]
除了这个规则没有其他的了吗，我这边测试没这个问题呢，方便的话可以加一下我微信：EVILCHEN__，我给您远程诊断一下。
<img width="1343" alt="image" src="https://github.com/gh0stkey/HaE/assets/24655118/027f43c1-663b-498c-adf0-b7461f081593">

**Comment by Qlng** [comment]
一更新就改配置格式，光改配置文件就要把我逼疯了
![image](https://github.com/gh0stkey/HaE/assets/39910823/fe35c6c9-f980-46e5-bbbd-45f3b56e7e69)
![image](https://github.com/gh0stkey/HaE/assets/39910823/75b78df2-df27-4dfc-a806-aecc24efb224)

**Comment by gh0stkey** [comment]
> 一更新就改配置格式，光改配置文件就要把我逼疯了 ![image](https://user-images.githubusercontent.com/39910823/283369094-fe35c6c9-f980-46e5-bbbd-45f3b56e7e69.png) ![image](https://user-images.githubusercontent.com/39910823/283369175-75b78df2-df27-4dfc-a806-aecc24efb224.png)

您这是什么逻辑？就2.5之后重构了配置文件，其他也没变动过配置文件结构。如果有什么需求可以提的哈，如果自定义规则不多的话手动添加一下，或者基于规则转换一下，不用花多长时间呢，实在不行，您把配置文件发出来我帮您转换都是一样的。

**Comment by gh0stkey** [comment]
> 卡一会儿然后请求记录列表是空的，我寻思是内存不够了？
> 
> ![图片](https://user-images.githubusercontent.com/86906331/283371280-234a113c-132f-4e5c-9b2c-5e93bed70369.png)

你是否自己新增了什么正则规则呢，这个提示很明显是正则导致的内存不足呢。

**Comment by gh0stkey** [comment]
麻烦你们自己有独立问题的自行开个ISSUE，按模板格式填写你们的信息，而不是在其他人的ISSUE下评论，这样我更没有办法去聚焦解决问题，谢谢！

**Comment by gh0stkey** [comment]
最新2.5.8版本已修复问题，自定义正则不复合规范导致整个HaE使用不了，该问题在下一个版本中修复，感谢反馈！
