### ISSUE TITLE
network error！

### ISSUE THREAD

**Issue by clingerxiangdingdang** [gh0stkey/HaE#154]
## 使用环境

```
HaE版本：
是否有自定义的HaE规则：
BurpSuite版本：
JDK版本：
操作系统版本：
```

## 问题详情

问题描述：无法加载规则库和配置文件

出现的场景：

## 解决建议

给个国内可用的节点下载更新规则库和配置文件。

**Comment by gh0stkey** [comment]
可以自行下载哈，国内暂时不考虑添加节点，没有免费的服务可用：https://raw.githubusercontent.com/gh0stkey/HaE/gh-pages/Rules.yml
