### ISSUE TITLE
关于使用过程中遇到的[BUG] 

### ISSUE THREAD

**Issue by WXxm0** [gh0stkey/HaE#155]
## 使用环境

```
HaE版本：2.5.11-jdk9
是否有自定义的HaE规则：有
BurpSuite版本：2022.3
JDK版本：JDK11
操作系统版本：Mac bigbur11
```

## 问题详情
问题描述：使用过程中，在Burpsuite HTTP history点击下一个存在高亮的URL时，MarkInfo界面没有自动刷新为下一个URL的Markinfo界面，需要先点击无触发HaE规则的URL后在返回点击则MarkInfo界面就才能更新到当前URL的MarkInfo界面

存在bug的场景:
![WechatIMG46](https://github.com/gh0stkey/HaE/assets/87017604/662eb948-5905-4459-abc2-ac190ad0b83b)
![WechatIMG47](https://github.com/gh0stkey/HaE/assets/87017604/32031258-42bf-4ab1-b456-8ee7dfe9d9d4)

## 解决建议
目前测试时暂时找到的解决方法：
![WechatIMG48](https://github.com/gh0stkey/HaE/assets/87017604/46c452bf-83b1-47ae-b4da-24c91bebeffd)
![WechatIMG49](https://github.com/gh0stkey/HaE/assets/87017604/5875d0c0-e397-4435-8cab-670ff4eb3558)
![WechatIMG50](https://github.com/gh0stkey/HaE/assets/87017604/a3ea6159-873e-4cbf-b084-e7902ece8c08)

**Comment by gh0stkey** [comment]
您的Burp更新一下吧，老版本Burp缓存问题。
