### ISSUE TITLE
[BUG] 为什么一直远程获取覆盖本地配置？

### ISSUE THREAD

**Issue by 0xAcctracy** [gh0stkey/HaE#157]
## 使用环境

```
HaE版本：HaE-2.5.11-J8.jar
是否有自定义的HaE规则：有
BurpSuite版本：burp2021
JDK版本：jdk13
操作系统版本：windows10
```

## 问题详情

问题描述：添加规则时就会获取远程文件覆盖掉本地文件

出现的场景：
采用的是在jar包下同级目录创建.config/HaE配置文件
![image](https://github.com/gh0stkey/HaE/assets/121917011/ed684cc2-017a-419e-bcb8-f69a39169553)
当前我的配置文件为14kb
![image](https://github.com/gh0stkey/HaE/assets/121917011/6129ea80-b214-4212-8fcc-7d44981e1566)
当我创建分组时，他自动抓取了远程配置到本地覆盖了我的配置文件
![image](https://github.com/gh0stkey/HaE/assets/121917011/23972307-c889-4833-bb9a-a600315652f7)

## 解决建议

无。

## 赞助

如果你觉得HaE好用，可以打赏一下作者，给作者持续更新下去的动力！

<div align=center>
<img src="https://raw.githubusercontent.com/gh0stkey/HaE/master/images/reward.jpeg" style="width: 30%" />
</div>

**Comment by gh0stkey** [comment]
没法复现你的问题
