### ISSUE TITLE
[BUG] 邮箱正则匹配不是很准确

### ISSUE THREAD

**Issue by enomothem** [gh0stkey/HaE#158]
![image](https://github.com/gh0stkey/HaE/assets/45089051/bbe7d901-3b6d-477c-8a7e-08faabc8a0fb)

使用+匹配多个字符
```bash
(([a-z0-9]+[_|\.])*[a-z0-9]+@([a-z0-9]+[-|_|\.])*[a-z0-9]+\.((?!js|css|jpg|jpeg|png|ico)[a-z]{2,5}))
```

改进后
![image](https://github.com/gh0stkey/HaE/assets/45089051/66691e64-cbfc-4733-acb2-ce3cec06566d)

**Comment by gh0stkey** [comment]
感谢反馈，这就同步更新上去。
