### ISSUE TITLE
没看到提匹配中文的正则

### ISSUE THREAD

**Issue by exp999fuck** [gh0stkey/HaE#159]
![1709113874511](https://github.com/gh0stkey/HaE/assets/161582212/ff02dc92-8a0b-4c42-99fb-cd19d757de8a)
然后正则是这样的
![1709113912554](https://github.com/gh0stkey/HaE/assets/161582212/181b9649-ab51-4eee-8cb4-adac7a9279bf)
结果
![1709113977552](https://github.com/gh0stkey/HaE/assets/161582212/da8fd681-c1b3-4fa4-992d-46f07f1fe1c5)
希望作者大大帮我一下

**Comment by enomothem** [comment]
正则匹配中文应该使用unicode吧，例如\u0012

**Comment by gh0stkey** [comment]
<img width="528" alt="image" src="https://github.com/gh0stkey/HaE/assets/24655118/8c41b884-eb75-45c1-aa5f-28047e6f3d9e">
<img width="544" alt="image" src="https://github.com/gh0stkey/HaE/assets/24655118/8f6bcee6-23cf-4331-b44e-bb8adc0c1259">
最新版本（2.6.1）没问题，感谢关注和反馈。
