### ISSUE TITLE
[需求] 支持 websocket 流量的匹配

### ISSUE THREAD

**Issue by No-Github** [gh0stkey/HaE#160]
实战中遇到了一个在 websocket 流量中泄露 assk 信息的目标

<img width="1090" alt="image" src="https://github.com/gh0stkey/HaE/assets/18167071/6746d394-292d-40bf-8181-54e832dde585">

感觉是不是可以吧这一块检测能力加上

**Comment by gh0stkey** [comment]
确实有这个需求，下一个版本中加入更新，感谢反馈！

**Comment by gh0stkey** [comment]
对于WebSocket流量匹配和提取的问题将在重构版本更新，因为旧的API不支持。
