### ISSUE TITLE
多个响应中的MarkInfo标签混在一起

### ISSUE THREAD

**Issue by Totriangle** [gh0stkey/HaE#161]
![image](https://github.com/gh0stkey/HaE/assets/20277339/88eeaef4-d505-4b64-8f78-8af97b3fc712)
选中某次请求后，正常应该只显示当前响应匹配的项，但实际会显示其他请求中的
使用的HaE版本是2.6

**Comment by gh0stkey** [comment]
您好，请不要使用BurpSuite汉化补丁，不兼容。

**Comment by Totriangle** [comment]
好的，谢谢，试了下好像是这个原因。

**Comment by tzf1003** [comment]
![image](https://github.com/gh0stkey/HaE/assets/46259700/cd3707d2-16bb-4337-a05a-f316127f207f)
修复方法，在Rules.yml文件修改以下内容

**Comment by gh0stkey** [comment]
你这是不让汉化汉化～
