### ISSUE TITLE
[优化建议]增加结果一键导出导入功能

### ISSUE THREAD

**Issue by JDXN** [gh0stkey/HaE#162]
## 优化建议
之前提到过学习log++，能对保存的bp项目的proxyHistory中一键导入历史记录，进行重新分析；但这可能会稍微复杂些，而且重新分析可能也会影响性能，可以考虑改为一键导出结果列表的功能，并可在下次打开bp项目直接导入结果列表以更新databoard
ps: 个人的小私心，希望能早日看到此功能的出现，望师傅们优先考虑

感谢师傅们的无私奉献，祝师傅们生活、事业 day day up !~

**Comment by gh0stkey** [comment]
感谢反馈，下一个版本中也许会有所体现。

**Comment by gh0stkey** [comment]
3.2版本已更新相应功能：https://github.com/gh0stkey/HaE/releases/tag/3.2
再次感谢，优秀的建议！
