### ISSUE TITLE
markinfo没有显示，databoard模块也不能使用

### ISSUE THREAD

**Issue by amassiverock** [gh0stkey/HaE#166]
## 使用环境

```
HaE版本：2.61
是否有自定义的HaE规则：无
BurpSuite版本：2.1
JDK版本：1.8
操作系统版本：win10
```

## 问题详情

问题描述：markinfo没有显示，databoard模块也不能使用

出现的场景：

## 解决建议

无。

## 赞助

如果你觉得HaE好用，可以打赏一下作者，给作者持续更新下去的动力！

<div align=center>
<img src="https://raw.githubusercontent.com/gh0stkey/HaE/master/images/reward.jpeg" style="width: 30%" />
</div>

**Comment by gh0stkey** [comment]
麻烦看下这里：https://github.com/gh0stkey/HaE/issues/130
