### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by qingchenhh** [gh0stkey/HaE#167]
## 使用环境

```
HaE版本：2.6.1
是否有自定义的HaE规则：是
BurpSuite版本：2023.1.1
JDK版本：java11
操作系统版本：Windows 10
```

## 问题详情

问题描述：

新增一些规则后，访问网站中的js特别大的时候或者访问很多带有较多js网站的时候会出现卡顿现象。
![image](https://github.com/gh0stkey/HaE/assets/37011241/236580ad-18d1-44f4-9b75-fc23a56057e5)
浏览器会一直卡着转圈，等匹配结束后再继续向下请求，导致访问特别卡，半天加载不出来页面。

出现的场景：

## 解决建议

建议不在访问的时候直接匹配特征，而是从访问后的history慢慢匹配特征，不影响正常的访问。

## 赞助

如果你觉得HaE好用，可以打赏一下作者，给作者持续更新下去的动力！

<div align=center>
<img src="https://raw.githubusercontent.com/gh0stkey/HaE/master/images/reward.jpeg" style="width: 30%" />
</div>

**Comment by No-Github** [comment]
调整 burp 启动时的参数吧,之前有个 issue 有讲过

**Comment by gh0stkey** [comment]
其他师傅已经解答过了，感谢关注。
