### ISSUE TITLE
[BUG] V2014.1.6版本安装BAPP store中的2.5.10后无法正常使用

### ISSUE THREAD

**Issue by ciscochao** [gh0stkey/HaE#169]
## 使用环境

```
HaE版本：BAPP store中的2.5.10
是否有自定义的HaE规则：无
BurpSuite版本：Professional V2024.1.1.6
JDK版本：
javac -version
javac 16.0.1

操作系统版本：
sw_vers
ProductName:	macOS
ProductVersion:	12.6
BuildVersion:	21G115
```

## 问题详情

问题描述：
安装好插件之后，也能自动更新config和Rules.yml。但是当访问存在敏感数据的URL时在proxy history中就是没有颜色区分，dadataboard中也没有任何数据。如果安装最新的2.6版本会报错。
出现的场景：
![image](https://github.com/gh0stkey/HaE/assets/37105273/5780cac9-1d3c-4726-9152-8fc132df7c67)
![image](https://github.com/gh0stkey/HaE/assets/37105273/3d4f110e-3967-44df-8c50-3f6fd61eec38)
![image](https://github.com/gh0stkey/HaE/assets/37105273/5caa177b-19bc-474b-b9d1-86b9fa074250)
![image](https://github.com/gh0stkey/HaE/assets/37105273/91264164-d6c0-44e4-bff0-d38a784a14c5)
安装2.6.1报错：
![image](https://github.com/gh0stkey/HaE/assets/37105273/7fe333a4-445d-474b-91f0-95879e206da3)

试了一下在Windows中同样的BP版本也是无法正常使用
## 解决建议

无。

## 赞助

如果你觉得HaE好用，可以打赏一下作者，给作者持续更新下去的动力！

<div align=center>
<img src="https://raw.githubusercontent.com/gh0stkey/HaE/master/images/reward.jpeg" style="width: 30%" />
</div>

**Comment by gh0stkey** [comment]
BAPP 没有同步更新，HaE最新版本请关注releases页面，下载对应Jar包，谢谢：https://github.com/gh0stkey/HaE/releases
