### ISSUE TITLE
[BUG] Databoard面板无显示

### ISSUE THREAD

**Issue by dd404x** [gh0stkey/HaE#170]
## 使用环境

```
HaE版本：2.6.1
是否有自定义的HaE规则：无
BurpSuite版本：24.1.1
JDK版本：17.0.9
操作系统版本：window 10
```

## 问题详情
Databoard面板无显示

问题描述：
Repeater模块中响应信息可以看到命中的内容，但是面板无法看到

出现的场景：
![image](https://github.com/gh0stkey/HaE/assets/19923974/3b0f560d-6bdc-4071-8237-86b2dcf7e59d)
![image](https://github.com/gh0stkey/HaE/assets/19923974/c2fb347f-7e94-4274-8ecd-eb182e1c0b65)

## 解决建议

无。

## 赞助

如果你觉得HaE好用，可以打赏一下作者，给作者持续更新下去的动力！

<div align=center>
<img src="https://raw.githubusercontent.com/gh0stkey/HaE/master/images/reward.jpeg" style="width: 30%" />
</div>

**Comment by dd404x** [comment]
知道了，插件没问题，面板host配置问题，初始安装插件host为空，搭建修改为**,添加host匹配规则就好啦

**Comment by gh0stkey** [comment]
默认肯定没有数据的，自己输入，下拉框给你选择。

**Comment by wan-xiang** [comment]
> 默认肯定没有数据的，自己输入，下拉框给你选择。

请问我这输入*也没有给下拉选择，**也没有全部匹配。就是没有数据
HaE版本：2.6.1(一开始是商店下载的，不显示，删了在github上下载，手动加载)
是否有自定义的HaE规则：无
BurpSuite版本：23.1.2  23.6 24.3.1都测试了
JDK版本：17.0.9
操作系统版本：window 11

**Comment by wan-xiang** [comment]
> > 默认肯定没有数据的，自己输入，下拉框给你选择。
> 
> 请问我这输入*也没有给下拉选择，**也没有全部匹配。就是没有数据 HaE版本：2.6.1(一开始是商店下载的，不显示，删了在github上下载，手动加载) 是否有自定义的HaE规则：无 BurpSuite版本：23.1.2 23.6 24.3.1都测试了 JDK版本：17.0.9 操作系统版本：window 11

测试了下kali上的burpsuite可以
java-21
BurpSuite版本：23.1.2

**Comment by nu0l** [comment]
> > 默认肯定没有数据的，自己输入，下拉框给你选择。
> 
> 请问我这输入*也没有给下拉选择，**也没有全部匹配。就是没有数据 HaE版本：2.6.1(一开始是商店下载的，不显示，删了在github上下载，手动加载) 是否有自定义的HaE规则：无 BurpSuite版本：23.1.2 23.6 24.3.1都测试了 JDK版本：17.0.9 操作系统版本：window 11

我也是遇到了这种问题，排查发现HaE的规则出了问题，不知道什么原因之前的规则被修改了。
<img width="519" alt="image" src="https://github.com/gh0stkey/HaE/assets/54735907/4c4e10d8-9636-473d-a15f-94d85e404df3">

**Comment by gh0stkey** [comment]
因为你的规则是老的，请仔细阅读README！
