### ISSUE TITLE
[遇到问题] 一直没有高亮显示

### ISSUE THREAD

**Issue by shadowundergo** [gh0stkey/HaE#171]
## 使用环境

```
HaE版本：2.5.10
是否有自定义的HaE规则：无，使用默认的
BurpSuite版本：2023.2、2024.2
JDK版本：1.8
操作系统版本：win10
```

## 问题详情

访问网站，在http history一直没有出现高亮，都是原本的白色

**Comment by gh0stkey** [comment]
请使用最新版本

**Comment by shadowundergo** [comment]
> 请使用最新版本

使用最新版本报错了，请问是什么问题呢
![1](https://github.com/gh0stkey/HaE/assets/106076571/67c4e2d7-0fc6-4b4f-afe5-18640c37aa00)

**Comment by gh0stkey** [comment]
你这也不是HaE的错误啊，你仔细看看
