### ISSUE TITLE
[优化建议] 建议区分同ip不同端口的目标

### ISSUE THREAD

**Issue by w4nd3r-hya** [gh0stkey/HaE#172]
1、实际使用过程中存在同ip不同端口的信息会混杂在一起，建议Dashboard里多加一个端口区分选择
2、config里已经加正则了，linkfinder里还是会出现png jpg等结尾的路径
<img width="528" alt="image" src="https://github.com/gh0stkey/HaE/assets/65856396/d2d13930-d140-4b6b-b8c6-fbf4cc06863d">

**Comment by gh0stkey** [comment]
第一个建议在更新计划中。第二点您提出的问题可以贴一下您的Linkfinder正则。

**Comment by gh0stkey** [comment]
HaE 3.0已更新。
