### ISSUE TITLE
[优化建议] 建议加一个不改变history tab颜色的设置

### ISSUE THREAD

**Issue by 0xWi11** [gh0stkey/HaE#173]
## 问题详情

问题描述：
我个人习惯给一些关键的请求标注上颜色，当自己的标注颜色的tab和插件标注颜色tab太多时，整个页面五彩斑斓的，很容易与自己手动标注的颜色混淆，从而影响工作效率。建议在项目中添加一个设置选项或者规则选项，允许用户选择是否改变历史记录标签页的颜色。
虽然这有点违背了项目的命名初衷，但是根据自身的经验和工作习惯，能自主决定是否改变历史记录标签页的颜色，可以提高工作效率，减少不必要的干扰。
![image](https://github.com/gh0stkey/HaE/assets/44541702/93e0ffbc-6932-4017-a205-aea5a6f16bf5)

**Comment by gh0stkey** [comment]
HaE高亮的目的就是让用户能直观的找到最有价值的报文，因此暂不采纳您的建议。另外，BurpSuite提供了Organizer就是专门用于记录、存储您认为值得关注的报文，也许您可以改变您的操作习惯，从而让HaE帮助您快速挖掘高危安全漏洞。
