### ISSUE TITLE
[BUG] HAE 2.6.1接收不到流量

### ISSUE THREAD

**Issue by WasteMaterial** [gh0stkey/HaE#174]
## 使用环境

```
HaE版本：2.6.1
是否有自定义的HaE规则：有
BurpSuite版本：2023.9.3
JDK版本：java17
操作系统版本：win11
```

## 问题详情

问题描述：
使用2.6.1时无法获取到流量进行颜色区分
![image](https://github.com/gh0stkey/HaE/assets/32891131/bc395897-dff7-4b27-afc2-543dc4b8a707)

Databoard功能中也无记录
![image](https://github.com/gh0stkey/HaE/assets/32891131/5039ee3a-e206-4513-8419-017cfaa3a3b6)

出现的场景：
history功能、hae的Databoard
## 解决建议

无。

## 赞助

如果你觉得HaE好用，可以打赏一下作者，给作者持续更新下去的动力！

<div align=center>
<img src="https://raw.githubusercontent.com/gh0stkey/HaE/master/images/reward.jpeg" style="width: 30%" />
</div>

**Comment by gh0stkey** [comment]
看下你的规则吧，你的规则估计不是最新版本的。
