### ISSUE TITLE
[优化]  使用Intruder爆破时每个包都会进行一次正则匹配会造成CPU资源浪费

### ISSUE THREAD

**Issue by bokaLA623** [gh0stkey/HaE#175]
## 问题详情

问题描述：
使用Intruder爆破时每个包都会进行一次正则匹配会造成CPU资源浪费，比如在跑大字典密码爆破的时候又正好返回包内容很多会变得很卡。暂时卸载插件可以缓解，但是在爆破完之前都不能使用HaE了。。

## 解决建议
设置一个可选按钮不对Intruder进行正则匹配？

## 赞助

如果你觉得HaE好用，可以打赏一下作者，给作者持续更新下去的动力！

<div align=center>
<img src="https://raw.githubusercontent.com/gh0stkey/HaE/master/images/reward.jpeg" style="width: 30%" />
</div>

**Comment by gh0stkey** [comment]
使用BurpSuite跑大批量的字典我建议是通过Turbo Intruder插件或者使用其他的工具，因为GUI本身就无法很好的处理大量的数据展示，使用Intruder确实会导致HaE不断的进行匹配从而消耗大量资源，不过目前经历有限，正在重构HaE中，因此暂时不考虑优化这个问题，感谢反馈。
