### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Huuuuuaaaa** [gh0stkey/HaE#176]
## 使用环境

```
HaE版本：
是否有自定义的HaE规则：
BurpSuite版本：2024.3.1.4
JDK版本：22 build 22+36-2370
操作系统版本：windows 10.0.19045
```

## 问题详情

问题描述：最新版Burp需要使用JDK22以上版本打开，最新HaE会导致Burp直接黑屏和卡住。

出现的场景：我把其他插件都去掉了，一个插件都不开正常，只开HaE，在repeater页面改包的时候一段时间后就会出现，暂不知道如何稳定触发。

## 解决建议

无。

**Comment by gh0stkey** [comment]
暂时没遇到该问题，可以下载一下最新的Jar包再尝试看看～

**Comment by Huuuuuaaaa** [comment]
我之前用的都比较正常，就是升级HAE到3.0，就有了

**Comment by gh0stkey** [comment]
如果不能稳定触发，那暂时没法定位到相关问题。感谢你的关注和支持，我们都一起再观察观察。

**Comment by Dreamy-elfland** [comment]
我也出现了同样的问题

**Comment by Huuuuuaaaa** [comment]
确实是存在这个问题的

**Comment by gh0stkey** [comment]
麻烦更新到BuriSuite目前最新版本2024.4.1试试

**Comment by Huuuuuaaaa** [comment]
好的

**Comment by Huuuuuaaaa** [comment]
问题还是存在

**Comment by gh0stkey** [comment]
麻烦加我微信：EVILCHEN__，沟通下

**Comment by king2035** [comment]
出现同样问题repeater发包的时候卡死2024.2.1.2

**Comment by Huuuuuaaaa** [comment]
目前测试发现在repeater复制粘贴的时候容易出现卡死，但是不清楚具体是因为哪个插件，建议大家如果怀疑某个插件，先把这个插件删掉，再用一段比较长的时间，来判断具体是哪个插件引起的。

**Comment by gh0stkey** [comment]
问题确认为HaE所导致，目前已经推送更新，请各位及时更新至3.0.1：https://github.com/gh0stkey/HaE/releases/tag/3.0.1
