### ISSUE TITLE
[优化建议] 

### ISSUE THREAD

**Issue by daydust** [gh0stkey/HaE#180]
建议在scope添加一个url或者path位置，因为request header匹配请求头，会匹配到Cookie，导致各种各样的脏数据或者误报，request body 又只能匹配请求体的内容，如果我想单独匹配path中的内容，就无法做到，这种情况我该如何解决呢？所以我认为加一个url或者path匹配会更灵活一些，我看有师傅提过这个优化建议，但好像没有进行采纳。。

**Comment by gh0stkey** [comment]
收到，下一个版本中加入Request First Line选项提供用户选择请求第一行

**Comment by gh0stkey** [comment]
已经更新：https://github.com/gh0stkey/HaE/releases/tag/3.0.1
