### ISSUE TITLE
[需求]是否新版hae仍然支持旧版burp

### ISSUE THREAD

**Issue by Superhero-zero** [gh0stkey/HaE#181]
因为bp不仅仅使用hae一个插件，还有其他插件，但是其他插件在新版的burp又不兼容，是否往后新版hae支持20之后版本的burp

**Comment by gh0stkey** [comment]
你说的情况其实并不存在，因为新版BurpSuite兼容旧的API，因此其他插件也可以使用。
由于HaE 3.0版本开始采用Montoya API进行开发，因此使用新版HaE需要升级你的BurpSuite版本（>=2023.12.1）。
