### ISSUE TITLE
[BUG] 请求中匹配到字符串，但是没有上色，无法从列表中筛选

### ISSUE THREAD

**Issue by daomeixiong1048** [gh0stkey/HaE#182]
请求中匹配到字符串，但是没有上色，无法从列表中筛选；且Databoard中也找不到此项。（响应中匹配到时能正常上色）

![图片](https://github.com/gh0stkey/HaE/assets/101961135/dda16640-423d-4e54-bd3f-ee5dc48bb87b)

**Comment by gh0stkey** [comment]
麻烦您按ISSUE模板填写您的信息，您使用的BurpSuite、HaE是什么版本，是否有自定义的正则。这样才方便诊断您的问题哈，我这边测试没有这个问题。

**Comment by daomeixiong1048** [comment]
我切换新版的burp后，问题解决了。感谢师傅 哇
