### ISSUE TITLE
[BUG] 控制台无法选中

### ISSUE THREAD

**Issue by daydust** [gh0stkey/HaE#184]
## 使用环境
```
HaE版本：3.0.1
是否有自定义的HaE规则：如下
name: GET 明文id
    loaded: true
    f_regex: (\b(?<!_)(id|\w+id)=(\d{1,12})\b(?![-_\\/]))
    s_regex: ''
    format: '{0}'
    color: green
    scope: request line
    engine: nfa
    sensitive: false
BurpSuite版本：2024.3.1
JDK版本：17
操作系统版本：win10
```

## 问题详情

问题描述：在使用该正则并搭配最新的request line时，颜色显示等一切都正常，也能够正确匹配，在控制台的总体数据也能查看到匹配结果，但是点击具体的匹配列想定位数据包时无法显示，如下

匹配*号正常显示
![屏幕截图 2024-05-11 095323](https://github.com/gh0stkey/HaE/assets/106896221/c9bfdb04-1ec0-4af1-9c7d-abb82d428e6f)
选中具体匹配数据则无法回显
![屏幕截图 2024-05-11 095352](https://github.com/gh0stkey/HaE/assets/106896221/bc1576e2-c79f-4507-a978-0ce59a6118f7)

其他的规则就一切正常，并没有看出我的这个规则有什么问题从而导致了这个bug

## 解决建议

无。

**Comment by gh0stkey** [comment]
确认BUG存在，下一版本进行修复

**Comment by gh0stkey** [comment]
3.0.2版本已修复该问题，再次感谢及时反馈问题。
地址：https://github.com/gh0stkey/HaE/releases/tag/3.0.2
