### ISSUE TITLE
[BUG] BURP卡死点情况

### ISSUE THREAD

**Issue by XF-FS** [gh0stkey/HaE#187]
## 使用环境

```
HaE 版本：3.0.2
有无自定义规则：无
BurpSuite 版本：2024.3.1。4
操作系统版本：macos
有无仔细阅读README：有
```

## 问题详情

问题描述：
从intruter转发数据包到repeater，或者从seach转发数据包到repeater时，有概率卡死burp
所有插件均正常使用，一直无出错，关闭hae整天都没有出现将burp打成无响应都情况，开启hae测试过程中大概2个小时回卡死一次burp，具体情况未知

出现的场景：
数据包发送到repeater

## 解决建议

可提供burp无响应软件日志

**Comment by king2035** [comment]
+1

**Comment by gh0stkey** [comment]
目前没遇到过你这个问题，麻烦请更新至BurpSuite最新版本再尝试下：[Professional / Community 2024.4.3](https://portswigger.net/burp/releases/professional-community-2024-4-3)

**Comment by gh0stkey** [comment]
@XF-FS 可以加下我微信：EVILCHEN__，方便帮您快速解决问题。

**Comment by gh0stkey** [comment]
3.1版本已修复
