### ISSUE TITLE
[BUG] 3.0.2版本HAE用着用着就g了

### ISSUE THREAD

**Issue by WasteMaterial** [gh0stkey/HaE#190]
## 使用环境

```
HaE 版本：
有无自定义规则：有，后进行update还原 HAE就自动闪退了，更换默认配置文件依然报错
BurpSuite 版本：2023.9.3
操作系统版本：win11
有无仔细阅读README：
```

## 问题详情

问题描述：
3.0.2版本HAE用着用着就g了，刚出那段时间还能正常用的
出现的场景：
正常安装，抓包就疯狂输出error
![image](https://github.com/gh0stkey/HaE/assets/32891131/5b24d6b7-a20e-47ae-8bb2-fbd15d856867)

## 解决建议
还没研究出来原因

**Comment by gh0stkey** [comment]
请仔细阅读README注意事项，谢谢。
由于HaE 3.0版本开始采用Montoya API进行开发，因此使用新版HaE需要升级你的BurpSuite版本（>=2023.12.1）。
