### ISSUE TITLE
[BUG] HaE无法正常生效，遇到对应指纹时并不能识别并标记

### ISSUE THREAD

**Issue by r4ynorth** [gh0stkey/HaE#193]
## 使用环境

```burp2024.03，JDK21

HaE 版本：burp官方商店插件
有无自定义规则：有
BurpSuite 版本：2024.03
操作系统版本：win11
有无仔细阅读README：
```

## 问题详情

HaE无法生效，距离如图的swaggerui页面并没有标记
![swagger](https://github.com/gh0stkey/HaE/assets/51961044/5381aa59-720d-4c46-91d8-9ec776506e7c)

配置页面无法点击修改原有规则。但可以新建rule进行edit
![Hae](https://github.com/gh0stkey/HaE/assets/51961044/1df55734-1b01-4d04-8254-a55f4b83b883)

另外查看extensions页面看报错信息也是空白（使用的是）

![error](https://github.com/gh0stkey/HaE/assets/51961044/d5f3ec4d-8304-4bd5-8912-2681a6ac59e3)
![image](https://github.com/gh0stkey/HaE/assets/51961044/55305363-f6ce-4544-9b28-cb71dcc52036)
![image](https://github.com/gh0stkey/HaE/assets/51961044/60881501-c319-445c-9cfe-5193ee7591a8)

出现的场景：

## 解决建议

无。

**Comment by gh0stkey** [comment]
提问题前先看看README吧，再看看Github发布的版本吧。
