### ISSUE TITLE
[优化建议]

### ISSUE THREAD

**Issue by 0neAtSec** [gh0stkey/HaE#195]
师傅在Hae里面能加一个配置吗，就是指定Hae插件只对Proxy模块/Repeater模块/Intruder模块/Logger模块......起作用。
有时候intruder比较大的字典时，hae插件也对它起作用，会很卡。

**Comment by gh0stkey** [comment]
下一版本中会考虑加入该功能，感谢建议。

**Comment by HuanYues** [comment]
希望下个版本一定要加入该功能，我目前也是一样的情况，特别是使用 Itruder 功能爆破时，CPU直接拉满到100，很卡很掉帧。然后爆破的速度也会变的很慢，关掉插件瞬间所有问题都就好了。之前一度以为是电脑出问题了。

**Comment by HuanYues** [comment]
> 下一版本中会考虑加入该功能，感谢建议。

希望下一个版本一定要加入该功能，我目前也是一样的情况，特别是使用Itruder 功能爆破时，CPU直接拉满到100，很卡很掉帧。然后爆破的速度也会变的很慢，关掉插件瞬间所有问题就好了。

**Comment by gh0stkey** [comment]
> > 下一版本中会考虑加入该功能，感谢建议。
> 
> 希望下一个版本一定要加入该功能，我目前也是一样的情况，特别是使用Itruder 功能爆破时，CPU直接拉满到100，很卡很掉帧。然后爆破的速度也会变的很慢，关掉插件瞬间所有问题就好了。

是否是默认规则、最新版本。理论上不会这么卡～这个功能在TODO了，敬请期待～

**Comment by HuanYues** [comment]
> > > 下一版本中会考虑加入该功能，感谢建议。
> > 
> > 
> > 希望下一个版本一定要加入该功能，我目前也是一样的情况，特别是使用Itruder 功能爆破时，CPU直接拉满到100，很卡很掉帧。然后爆破的速度也会变慢，关掉插件瞬间所有问题就好了。
> 
> 是否是默认规则、最新版本。理论上不会这么卡～这个功能在TODO了，敬请期待～

我已经找到原因了，我这里主要原因是自己没事又加了很多规则，导致使用爆破的时候估计 Hae 匹配不过来了，匹配的的太慢了，然后就会CPU拉满，爆破的速度也会很慢。使用新版默认的规则，如果自己不加太多新的规则情况下，的确不会有什么太大影响。

**Comment by gh0stkey** [comment]
@HuanYues 添加自定义规则导致卡顿，我觉得不光是自定义规则的数量多，还有一个可能你使用的正则表达式并不规范导致存在ReDoS因此影响正常使用。

**Comment by enomothem** [comment]
> @HuanYues 添加自定义规则导致卡顿，我觉得不光是自定义规则的数量多，还有一个可能你使用的正则表达式并不规范导致存在ReDoS因此影响正常使用。

对的，规则多应该不成问题，主要是正则的匹配范围

**Comment by ll160803** [comment]
大佬 还有burp其他插件自动扫描的时候，会产生数据，hae也会对这些流量进展抓取匹配

**Comment by panzhen1992** [comment]
M1 mac 电脑使用2023.12.1的burp，高亮失效，是啥原因呀？
<img width="1277" alt="image" src="https://github.com/user-attachments/assets/0c2572ee-5161-4c23-828d-afe55407a9a2">
