### ISSUE TITLE
插件加载后怎么没在标签栏看到？功能倒是正常

### ISSUE THREAD

**Issue by shengxiaq** [gh0stkey/HaE#196]
![图片](https://github.com/gh0stkey/HaE/assets/50311735/e11bc4d9-149a-4689-94b8-d5e838649fcc)

**Comment by gh0stkey** [comment]
请仔细阅读README，查看自己是否满足使用要求。
<img width="830" alt="image" src="https://github.com/gh0stkey/HaE/assets/24655118/bbd7512e-31e0-4295-af84-6fe89283ab24">

**Comment by NatsuGaOwatta** [comment]
今天也遇到这问题了，Burp 2024.6.6 + HaE 3.3.1，然后发现 Unload Burp Bounty Pro 这个插件或者把 HaE 的位置移动到 Burp Bounty Pro 上边就显示出来了🤣

**Comment by shengxiaq** [comment]
> 今天也遇到这问题了，Burp 2024.6.6 + HaE 3.3.1，然后发现 Unload Burp Bounty Pro 这个插件或者把 HaE 的位置移动到 Burp Bounty Pro 上边就显示出来了🤣

我后面也发现了，没想到这插件与burp bounty pro有冲突😂跟其他插件搭配倒没什么
