### ISSUE TITLE
[BUG] 问题标题

### ISSUE THREAD

**Issue by panzhen1992** [gh0stkey/HaE#198]
M1 mac 配置了swagger，插件识别到，也不高亮，重新加载了，也不行，HaE用的最新的版本，burp用的2023-12-1的版本。

**Comment by gh0stkey** [comment]
由于HaE 3.0版本开始采用Montoya API进行开发，因此使用新版HaE需要升级你的BurpSuite版本（>=2023.12.1）。

**Comment by panzhen1992** [comment]
burp版本是2023.12.1，而且插件没有报任何错，就是不知道为啥不高亮

**Comment by gh0stkey** [comment]
你的规则截图

**Comment by panzhen1992** [comment]
<img width="1287" alt="image" src="https://github.com/user-attachments/assets/945ad891-c644-440a-a312-02382ecd4f90">
发现点击编辑，wu无法编辑，不响应

**Comment by panzhen1992** [comment]
<img width="1294" alt="image" src="https://github.com/user-attachments/assets/49bb4390-c3b1-4d2b-9f21-7cead7d1a74c">
匹配没有任何的高亮，像是配置文件不起作用

**Comment by gh0stkey** [comment]
兄弟，你配置文件都有问题，F-Regex S-Regex都是空的，删除配置文件重新加载吧

**Comment by panzhen1992** [comment]
好了，可以了，感谢大佬
