### ISSUE TITLE
[BUG] preview双击或两次点击会显示一直loading

### ISSUE THREAD

**Issue by zhefox** [gh0stkey/HaE#199]
## 使用环境

```
HaE 版本：
有无自定义规则：无
BurpSuite 版本：2024.1.1.1
操作系统版本：win11最新
有无仔细阅读README：无
```

## 问题详情

问题描述：
会一直loading
![QQ_1721812968520](https://github.com/user-attachments/assets/8f0f6bc4-e373-48cf-b8fa-f80358ba3745)

出现的场景：
双击或者两次点击同一个url查看详情
## 解决建议
当前缓解使用方法是，点击其他的url，然后再点击回来
无。

**Comment by gh0stkey** [comment]
问题已知，目前来说整体上不影响使用。问题会在后续修复，感谢反馈。
