### ISSUE TITLE
导入问题

### ISSUE THREAD

**Issue by xxsmile123** [gh0stkey/HaE#2]
使用说明中提到，这里用的是python2.7版本的site-packages。但是在windows10平台上导入的时候，会报错。插件的存放位置的路径全是英文没有中文，python2的安装路径也是全英文。所以排除了路径的问题。
      至于文件夹的名字，没有做任何修改。
![image](https://user-images.githubusercontent.com/43473886/79035293-a8589800-7bef-11ea-98c3-72620e593cd4.png)
虽然用python2导入了这个模块，在导入这个插件的时候还是会出报上面的错误。

**Comment by 780000063** [comment]
这里作者没讲清楚，因为这个插件调用了jsbeautifier。你没安装这个模块就会报错。安装下就好了： pip install jsbeautifier

**Comment by gh0stkey** [comment]
> 这里作者没讲清楚，因为这个插件调用了jsbeautifier。你没安装这个模块就会报错。安装下就好了： pip install jsbeautifier

@780000063 已经说的很清楚了，感谢指正。
