### ISSUE TITLE
java version "22" 2024-03-19无法正常使用插件

### ISSUE THREAD

**Issue by fleabane1** [gh0stkey/HaE#200]
## 使用环境

```
HaE 版本：3.3
有无自定义规则：无
BurpSuite 版本：2024.6.3
操作系统版本：Windows 10
有无仔细阅读README：有
```

## 问题详情

问题描述：加载插件后虽然提示成功，但是并无新的标签展示
![image](https://github.com/user-attachments/assets/0d89163e-35d4-44c9-b9e2-12e8f4367689)

出现的场景：正常加载过程中出现的情况，无法看到原有的面板

## 解决建议

无。

**Comment by gh0stkey** [comment]
麻烦删除配置文件之后重新加载

**Comment by fleabane1** [comment]
我这边重新删除配置文件加载了下，还是不行，感觉像是新版本BP不兼容的问题，有些插件也显示不出来，我截个全图给你看看
![image](https://github.com/user-attachments/assets/2911d6d7-bae0-4681-9d27-de05bd2039dd)

**Comment by gh0stkey** [comment]
我使用的就是这个版本，没有文件，你删除的是整个文件夹吗

**Comment by fleabane1** [comment]
给你截图的时候，只是删除了Config.yml，我重新删除了包含配置文件和规则的文件夹，然后重新加载了，还是那个样子，感觉像是我删除了下面这些东西导致的。之前用的时候也是正常的，然后抓包除了问题，我就删除了下，重新用这个版本的，抓包问题解决了，插件显示问题又来了，说不来是什么问题，但是那个boundty的文件是可以正常显示的，就很迷。
![image](https://github.com/user-attachments/assets/4ba2f1c3-1971-4381-8ee5-50240011ee4c)

**Comment by gh0stkey** [comment]
加微信解决吧：EVILCHEN__
