### ISSUE TITLE
[BUG] Burp专业版本地破解后高亮不显示

### ISSUE THREAD

**Issue by Dillon86** [gh0stkey/HaE#203]
## 使用环境
win11
```
HaE 版本：
3.3.1
BurpSuite 版本：
Burp Professional 2023.5.1
操作系统版本：win11
有无仔细阅读README：有
```

## 问题详情

问题描述：下载github release版本hae插件，安装插件。

出现的场景：
URL中出现敏感的手机号，身份证号，proxy-> http history中不高亮显示
![t](https://github.com/user-attachments/assets/92cb01df-c312-407c-9cb5-ef58bc1d58c1)

## 解决建议

无。

**Comment by gh0stkey** [comment]
删除历史规则，然后重新加载
