### ISSUE TITLE
[BUG] 编译问题

### ISSUE THREAD

**Issue by EmptyZeroRain** [gh0stkey/HaE#205]
在使用idea 手动bulid时会提示报错
HaE/src/main/java/hae/component/board/table/AIPower.java:7: 错误: 程序包com.google.gson不存在
import com.google.gson.Gson;  
HaE/src/main/java/hae/component/board/table/AIPower.java:13: 错误: 程序包okhttp3不存在
import okhttp3.*; 
需要手动在
build.gradle文件中，新加
dependencies {
    implementation 'com.google.code.gson:gson:2.8.9'
    implementation 'com.squareup.okhttp3:okhttp:4.9.3'
}
再次bulid 不会提示报错

**Comment by gh0stkey** [comment]
确实，忘记同步了依赖信息了，感谢反馈，这就去更新。
