### ISSUE TITLE
加载HAE不显示敏感信息

### ISSUE THREAD

**Issue by dydymm** [gh0stkey/HaE#207]
在抓包时hae未标注存在敏感信息的数据包

**Comment by gh0stkey** [comment]
仔细阅读README！！！！

**Comment by dydymm** [comment]
感谢！没注意规则变更了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gh0stkey/HaE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月30日(星期五) 下午3:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gh0stkey/HaE] 加载HAE不显示敏感信息 (Issue #207)





 
仔细阅读README！！！！
