### ISSUE TITLE
[BUG] 插件添加失败

### ISSUE THREAD

**Issue by kN4im3** [gh0stkey/HaE#208]
## 使用环境
JDK 11 2022 Burp
```
HaE 版本：3.3.2
有无自定义规则：
BurpSuite 版本：
操作系统版本：
有无仔细阅读README： 有
```

## 问题详情

问题描述：
使用 BURP 添加插件报异常：
![image](https://github.com/user-attachments/assets/955e78cc-4b1a-438a-95dc-54e89c09863e)

出现的场景：

## 解决建议

无。

**Comment by gh0stkey** [comment]
请仔细阅读项目README，谢谢
