### ISSUE TITLE
jar 包使用不了

### ISSUE THREAD

**Issue by zjz677** [gh0stkey/HaE#210]
初次装载HaE会从Jar包中加载离线的规则库，如果更新的话则会向官方规则库地址拉取https://raw.githubusercontent.com/gh0stkey/HaE/gh-pages/Rules.yml，配置文件（Config.yml）和规则文件（Rules.yml）会放在固定目录下：

Linux/Mac用户的配置文件目录：~/.config/HaE/
Windows用户的配置文件目录：%USERPROFILE%/.config/HaE/
除此之外，您也可以选择将配置文件存放在HaE Jar包的同级目录下的/.config/HaE/中，以便于离线携带。

这个我搞不明白mac 应该怎么配置 我直接装的jar包 会给我提示去github

**Comment by gh0stkey** [comment]
HaE现在默认规则都在Jar包里，安装就行了，怎么可能用不了？

**Comment by zjz677** [comment]
![Uploading 截屏2024-09-18 22.32.40.png…]()
我扩展加入jar包以后 他就自动跳出来这个了

**Comment by gh0stkey** [comment]
图片看不到，麻烦仔细阅读README，并按issue的规则来提问题，谢谢。
