### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by xiaoxiaolbt** [gh0stkey/HaE#212]
## 使用环境

```
HaE 版本：3.3.3
有无自定义规则：无
BurpSuite 版本：2023.10.3.3
操作系统版本：win10
有无仔细阅读README：有
```

## 问题详情

问题描述：加载插件后规则是拉取成功的，但是会报NoSuchMethodError的错
java.lang.NoSuchMethodError: 'java.lang.String burp.api.montoya.http.message.requests.HttpRequest.fileExtension()'

出现的场景：

**Comment by gh0stkey** [comment]
使用一个开源项目之情要不仔细读一下README？感谢。

注意事项中提到:`HaE 3.0版本开始采用Montoya API进行开发，使用新版HaE需要升级你的BurpSuite版本（>=2023.12.1）。`
