### ISSUE TITLE
[BUG] 在Burp v2024.8中使用最新版HaE无法正常显示标记

### ISSUE THREAD

**Issue by prismbreak** [gh0stkey/HaE#214]
## 使用环境

```
HaE 版本：3.3.3
有无自定义规则：无
BurpSuite 版本：2024.8
操作系统版本：Win11
是否阅读README：是
是否知晓注意事项：是
是否查阅历史ISSUE：是
```
在Burp v2024.8版本下使用最新版HaE 3.3.3时无法正常显示标记：
![image](https://github.com/user-attachments/assets/92302b4f-e390-47ed-9da5-ec17d0bc18fe)
![image](https://github.com/user-attachments/assets/e4f3db75-ee3c-47d5-af68-3fbe1d780d84)

而使用HaE 2.4.8正常：
![image](https://github.com/user-attachments/assets/35cd6770-750f-44fb-9eb7-eab225d3bc45)
![image](https://github.com/user-attachments/assets/8c8defc0-9837-472f-850c-427efff6eccc)

**Comment by gh0stkey** [comment]
麻烦更新下你的规则：删除配置文件重新加载HaE。
