### ISSUE TITLE
[BUG] WINDOWS PATH 规则改进建议

### ISSUE THREAD

**Issue by 4ra1n** [gh0stkey/HaE#217]
我测试 WINDOWS DIR 这个 RULE 可以改进下

```txt
[^\w](([a-zA-Z]:\\(?:\w+\\?)*)|([a-zA-Z]:\\(?:\w+\\)*\w+\.\w+))
```

可以匹配到：C:\Users\Public\Documents\file 没问题

有以下一些建议：

- 匹配出的结果好像是开头包含了多余的空格，需要手动 `trim` 下
- 无法匹配 C:\Users\Public\Documents\file.txt （我不知道是否符合预期，预期是只匹配目录不考虑文件嘛）
- C:\\\\Users\\\\Public\\\\Documents\\\\file （考虑到某些情况确实是转义后的 PATH 情况）
- C:\Program Files\test （目前似乎是无法匹配到包含空格的路径）

**Comment by 4ra1n** [comment]
C:\\\\Users\\\\Public\\\\Documents\\\\file

两个 \\ 会被 GITHUB 转义这里写成四个，主要是表达出现两个的情况可以报出

**Comment by 4ra1n** [comment]
参考截图

![image](https://github.com/user-attachments/assets/70ec84d8-18da-42b8-a14d-49740a02bb56)

**Comment by gh0stkey** [comment]
感谢反馈，确实存在相关问题，下一个版本发布时会同步优化

**Comment by AabyssZG** [comment]
`^([a-zA-Z]:\\(?:[^<>:/\\|?*]+\\)*)([^<>:/\\|?*]+(?:\.[^<>:/\\|?*]+)?)?$`

emmmm，还需要解决一下对于 `C:\\Users\\Public\\Documents\\file` 的匹配，得再想想

![屏幕截图 2024-10-24 111857](https://github.com/user-attachments/assets/8447a268-037b-4231-a9c7-c5dad72ec4ff)

**Comment by AabyssZG** [comment]
`^([a-zA-Z]:\\\\?(?:[^<>:/\\|?*]+\\\\?)*)([^<>:/\\|?*]+(?:\.[^<>:/\\|?*]+)?)?$`

解决了对于 `C:\\Users\\Public\\Documents\\file` 的匹配，完美！

![屏幕截图 2024-10-24 112435](https://github.com/user-attachments/assets/a4a6d075-5b21-47a1-a33b-b286a8cd494f)

**Comment by gh0stkey** [comment]
问题已由 @AabyssZG 解决，并同步了PR，已Merged，感谢反馈和建议。
