### ISSUE TITLE
[BUG] 问题标题

### ISSUE THREAD

**Issue by amoy6228** [gh0stkey/HaE#220]
## 使用环境

```
HaE 版本：3.3.4
有无自定义规则：无
BurpSuite 版本：2024.8.1
操作系统版本：Windows10 专业版
是否阅读README：是
是否知晓注意事项：是
是否查阅历史ISSUE：是
```

## 问题详情

问题描述：
![image](https://github.com/user-attachments/assets/e1d66b40-ce6a-4eef-831c-b06eee59afec)

出现的场景：
调用阿里云AI时报错 有余额
## 解决建议

无。

**Comment by gh0stkey** [comment]
> HaE 3.3版本开启了AI+新功能，该功能目前仅支持阿里的Qwen-Long模型（支持超长文本）和月之暗面的moonshot-v1-128k模型（支持短文本），请配置和使用时注意。

你要在平台上开启Qwen-Long这个模型权限才行
