### ISSUE TITLE
Linkfinder规则优化

### ISSUE THREAD

**Issue by m4ra7h0n** [gh0stkey/HaE#223]
```
/*
    const debuggerA = urlParams.get('debug');
if (debuggerA === null) { 
   
} else {
        var oReq = new XMLHttpRequest();
        oReq.addEventListener("load", reqListener);
        oReq.open("GET", "?f=/generate-credentials");
        oReq.send();

      function reqListener () {
        document.write(this.responseText);
      }
      
}*/
```
匹配不到这个`?f=/generate-credentials`
然后我看那个规则一堆，也不想看，你们给完善一下

这里的`https://bugbountytraining.com/assets/js/script.min.js`

看看，多加个`(\?[a-zA-Z0-9_\-/]+(?:=[a-zA-Z0-9_\-/]+)?)`在`"|'`里

**Comment by gh0stkey** [comment]
Linkfinder顾名思义，链接寻找，你这种只是单纯的参数传递，而不是一个链接，因此匹配不到，按你的说法添加一个单独的就可以了，后续我们会考虑优化相关内容，感谢建议。

**Comment by m4ra7h0n** [comment]
不是/generate-credentials这个是个目录
