### ISSUE TITLE
无事发生，无需解答，抱歉打扰了请关闭此issues

### ISSUE THREAD

**Issue by wobuyaotutou** [gh0stkey/HaE#225]
## 使用环境

```
HaE 版本：3.3.4/3.3.3
有无自定义规则：无
BurpSuite 版本：2023.5.
操作系统版本：win11
是否阅读README：是
是否知晓注意事项：是
是否查阅历史ISSUE：是
```

## 问题详情

问题描述：无法使用
![image](https://github.com/user-attachments/assets/0dd43acd-e41c-4619-aa39-4815b8f7a7e9)
![image](https://github.com/user-attachments/assets/b020ea9e-3fc7-4ea3-835a-4519f19e65ef)

出现的场景：

## 解决建议

无。

**Comment by gh0stkey** [comment]
好的，感谢反馈
