### ISSUE TITLE
[BUG] 分块传输或流式响应卡死, 卸载插件立马解决

### ISSUE THREAD

**Issue by 15Aliak21** [gh0stkey/HaE#226]
HaE 版本：3.3.3/4
访问下面两个主站会默认请求一些资源导致卡死, 好像是这两个资源
https://curlconverter.com/images/firefox@2x.webp
https://static.easychuan.cn/main-es2015.0bd8ac8e2f7a876d331e.js

已解决: 似乎是某些自定义规则导致的

**Comment by gh0stkey** [comment]
经测试，暂时没遇到该问题。感谢反馈，自定义规则需要注意防止出现ReDoS问题。
<img width="1010" alt="image" src="https://github.com/user-attachments/assets/e9b27f33-4f38-49b1-b161-9ec53fbd4f0b">
