### ISSUE TITLE
[Feature Request] Add an option to set color none

### ISSUE THREAD

**Issue by xvapourx** [gh0stkey/HaE#228]
Just add an option to set colour as it is without changing it to anything.

**Comment by gh0stkey** [comment]
You can also uncheck: Enable active http message handler, so that colors and notes are not set.

**Comment by xvapourx** [comment]
Disabling the active http message handler disables all colors. I want the colors and notes to be enabled but on certain regex matches, let the color be none (no changes) only notes addition.
