### ISSUE TITLE
[BUG] 问题标题

### ISSUE THREAD

**Issue by The-Dark-Horse-prince** [gh0stkey/HaE#229]
## 使用环境

```
HaE 版本：
有无自定义规则：
BurpSuite 版本：
操作系统版本：
是否阅读README：
是否知晓注意事项：
是否查阅历史ISSUE：
```

## 问题详情

问题描述：
bp最新版本不适配
![image](https://github.com/user-attachments/assets/e0584782-36f2-4296-b7b1-ae0c1b5ff01d)

出现的场景：

**Comment by gh0stkey** [comment]
首先麻烦您按模板填写问题，不然无法诊断，其次请检查自己的规则是否是最新版本规则。
