### ISSUE TITLE
你好，已经配置key了，这个AI功能应该怎么使用

### ISSUE THREAD

**Issue by kite0897** [gh0stkey/HaE#230]
![image](https://github.com/user-attachments/assets/ff700f3b-45c4-4c95-b5f4-c0454935e047)
你好，已经配置key了，这个AI功能应该怎么使用

**Comment by gh0stkey** [comment]
首先请确保你的Key是Qwen-Long模型，不然是不支持的。其次你可以在数据提取页面（MarkInfo/Databoard）的右下角选择Al Empowered - Alibaba / Kimi，用于精炼提取结果。
