### ISSUE TITLE
[BUG] update rules会导致插件被移除

### ISSUE THREAD

**Issue by Xiaosesh** [gh0stkey/HaE#231]
## 使用环境

```
HaE 版本：最新版
有无自定义规则：默认规则
BurpSuite 版本：最新版
操作系统版本：最新版
是否阅读README：已阅
是否知晓注意事项：知晓
是否查阅历史ISSUE：已查
```

## 问题详情

问题描述：如题，点击更新按钮会导致插件被禁用，只能手动重新启用

出现的场景：HAE-配置-update

## 解决建议

确保更新可用。

**Comment by Xiaosesh** [comment]
bpversion: v2024.2.1

**Comment by gh0stkey** [comment]
HaE官方规则库存放在[Github](https://raw.githubusercontent.com/gh0stkey/HaE/gh-pages/Rules.yml)上，因此点击Update升级HaE官方规则库时需使用代理（BApp审核考虑安全性，不允许使用CDN）。
