### ISSUE TITLE
[BUG] 问题标题

### ISSUE THREAD

**Issue by Long209** [gh0stkey/HaE#232]
## 使用环境

```
HaE 版本：最新版
有无自定义规则：无
BurpSuite 版本：2024.9
操作系统版本：win11
是否阅读README：是
是否知晓注意事项：是
是否查阅历史ISSUE：是
```

## 问题详情
点击uodate会自动移除插件，发现链接gh0stkey/HaE/gh-pages/Rules.yml已经404了，使用代理无效
问题描述：

出现的场景：

## 解决建议

无。

**Comment by Long209** [comment]
点击update

**Comment by gh0stkey** [comment]
在线规则库已经删除，后续不再使用，如想更新官方规则可以删除配置文件，然后重新加载即可，内置规则均为最新规则。
