### ISSUE TITLE
卡顿问题

### ISSUE THREAD

**Issue by TFour123** [gh0stkey/HaE#234]
能否优化加载网站js过多而导致的网站加载慢和bp的卡顿问题

**Comment by gh0stkey** [comment]
一、卡顿并不是HaE直接功能导致，而是BurpSuite官方提供的API设计逻辑有问题，将请求和响应的高亮注释放在了消息接收和处理的逻辑内；
二、对于该问题，如果你不想启用高亮注释并且只想抓包查看，可以考虑在Config - `Enable active http message handler`中取消勾选，直接在Databoard上查看这样速度会提示很大一截。
