### ISSUE TITLE
burp 2021.7-2021.8兼容性问题

### ISSUE THREAD

**Issue by winezer0** [gh0stkey/HaE#26]
在高版本情况下，proxy模块如果报文有关键字被匹配高亮，点击报文后会发现，大窗口就看不到报文内容了，小窗口还能看（刚开始打开的时候能用）

![image](https://user-images.githubusercontent.com/46115146/128446102-8082f543-a4fe-4efc-8983-d81953638e1f.png)
![image](https://user-images.githubusercontent.com/46115146/128446144-f6c9845c-450a-4fdb-a72c-449c925529e2.png)

**Comment by gh0stkey** [comment]
很抱歉，这个问题上个月2021.7版本就发现了，我一直尝试积极的联系BurpSuite官方，这跟插件本身没有关系，是BurpSuite本身出现了BUG，他们也承认这是一个BUG，复现了但至今没有修复。

**Comment by gh0stkey** [comment]
我又给他们发了一封邮件，并且我打算在twitter上diss一下他们，等待修复吧，感谢！

**Comment by winezer0** [comment]
好的，非常感谢。我也发了一封邮件给他们

**Comment by gh0stkey** [comment]
一个好消息：BurpSuite官方终于在2021.8.1版本中修复了插件扩展Tab的BUG，HaE可以正常使用了～
