### ISSUE TITLE
2021.8.1 版本 + java15 + 2.0.6 导入报错

### ISSUE THREAD

**Issue by kingween** [gh0stkey/HaE#29]
![image](https://user-images.githubusercontent.com/16068633/129661994-1e9d1bd1-dd52-465c-8138-63a6c2416055.png)

**Comment by gh0stkey** [comment]
可以正常使用么

**Comment by kingween** [comment]
> 可以正常使用么

不能正常使用 mac

**Comment by gh0stkey** [comment]
应该是JAVA版本的问题，建议使用burp官方自带的dmg安装

**Comment by kingween** [comment]
> 应该是JAVA版本的问题，建议使用burp官方自带的dmg安装

那是要用java什么版本？

**Comment by gh0stkey** [comment]
我看了下我本机也是15，Burpsuite自带的的就是这个版本，从上述代码来看应该是初始化就出了问题，可以看下你的配置文件是否正确，也可以列一下，我帮你看看。
