### ISSUE TITLE
身份证正则15/18

### ISSUE THREAD

**Issue by novysodope** [gh0stkey/HaE#3]
[(^[1-9]\d{5}(18|19|([23]\d))\d{2}((0[1-9])|(10|11|12))(([0-2][1-9])|10|20|30|31)\d{3}[0-9Xx]$)|(^[1-9]\d{5}\d{2}((0[1-9])|(10|11|12))(([0-2][1-9])|10|20|30|31)\d{2}[0-9Xx]$)](https://www.cnblogs.com/xtqg0304/p/9529721.html)

￣▽￣

**Comment by gh0stkey** [comment]
已添加到正则库同步Readme，修改后的正则为：

```regexp
[^0-9]([1-9]\d{5}(18|19|([23]\d))\d{2}((0[1-9])|(10|11|12))(([0-2][1-9])|10|20|30|31)\d{3}[0-9Xx])|([1-9]\d{5}\d{2}((0[1-9])|(10|11|12))(([0-2][1-9])|10|20|30|31)\d{2}[0-9Xx])[^0-9]
```
