### ISSUE TITLE
建议添加HTTP history的Comment提示功能

### ISSUE THREAD

**Issue by sftrwo** [gh0stkey/HaE#34]
我感觉通过颜色高亮的方式，还是无法直接知道插件匹配到了什么信息。
如果能在HTTP History的Comment字段中针对每一个规则加上文字的提示是不是会方便一些？

我是在用了官方Bapp Store里面的JSON Web Tokens插件后发现的，如果作者认为有必要添加这个功能的话，可以参考这个插件。

![image](https://user-images.githubusercontent.com/49747619/132955044-52638864-803b-44da-bd50-1e3e7ed9b459.png)

**Comment by gh0stkey** [comment]
这个已经在Todo List中了，感谢。

**Comment by gh0stkey** [comment]
正好有时间，加上去了，感谢：https://github.com/gh0stkey/HaE/releases/tag/2.1

**Comment by sftrwo** [comment]
太棒了，神速。

**Comment by sftrwo** [comment]
太棒了，神速。
