### ISSUE TITLE
提交规则

### ISSUE THREAD

**Issue by DevilMayCrying** [gh0stkey/HaE#39]
source-map正则
color: green
    engine: nfa
    loaded: true
    name: source-map
    regex: (app\b\.\w+\.js\.map)
    scope: any

**Comment by gh0stkey** [comment]
这个source-map的正则是不是可以简化一下，变成(.js.map)

**Comment by DevilMayCrying** [comment]
key师傅  sourcemap打包后的文件格式不都是app.xxx.map这样的么？😑

**Comment by DevilMayCrying** [comment]
> 这个source-map的正则是不是可以简化一下，变成(.js.map)

是的呢 有些sourcemap打包后格式不是app.xxx.map也可以囊括😀

**Comment by gh0stkey** [comment]
OK，已收录，感谢。

**Comment by gh0stkey** [comment]
![image](https://user-images.githubusercontent.com/24655118/149885686-1944b3fc-2a01-485b-b57e-93b143a2adbd.png)
