### ISSUE TITLE
java 15, Burp v2021.6.2, 加载插件的时候未初始化配置文件导致报错，能否提供一下两个配置文件的模板

### ISSUE THREAD

**Issue by NiuLk** [gh0stkey/HaE#44]
java 15, Burp v2021.6.2, 加载插件的时候未初始化配置文件导致报错，能否提供一下两个配置文件的模板

**Comment by gh0stkey** [comment]
感谢反馈，该BUG已经修复：https://github.com/gh0stkey/HaE/releases/tag/2.1.5
