### ISSUE TITLE
启用插件开启多条规则后，遇到chunk js的站点加载时间极慢

### ISSUE THREAD

**Issue by Is4b3lla3** [gh0stkey/HaE#48]
当插件使用众多规则后
![image](https://user-images.githubusercontent.com/37106292/156889790-ae00d6bc-c921-4e7d-8562-3de256168096.png)

遇到webpack打包的站点，chunk js文件过大，加载就会十分缓慢，关掉HAE插件就不存在这个问题，有没有办法可以优化一下呢

![image](https://user-images.githubusercontent.com/37106292/156889719-54b13d63-f7ca-4b2a-b5e6-9a65999d883c.png)

**Comment by gh0stkey** [comment]
HaE的核心是基于BurpSuite API -> processHttpMessage去处理这些请求和响应，而这个API又直接影响着Proxy，之前有考虑过该用doPassiveScan，虽然该API不影响加载流程，但该API不会重复去匹配相同的请求，并且无法设置高亮、Comment等工作。

**Comment by gh0stkey** [comment]
所以，目前没有什么比较好的方法，请见谅，可以检查下自己的HaE规则中是否有存在ReDoS的。

**Comment by Is4b3lla3** [comment]
规则用的是公共规则网站里的内容😂

**Comment by Is4b3lla3** [comment]
> 所以，目前没有什么比较好的方法，请见谅，可以检查下自己的HaE规则中是否有存在ReDoS的。

规则用的是公共规则网站里的内容
