### ISSUE TITLE
提交几个正则

### ISSUE THREAD

**Issue by epony4c** [gh0stkey/HaE#5]
{
	"secret_key": {
		"loaded": true,
		"highlight": true,
		"regex": "([Ss](ecret|ECRET)_?[Kk](ey|EY))",
		"extract": true,
		"color": "red"
	},
	"shior": {
		"loaded": true,
		"highlight": true,
		"regex": "(rememberMe=delete)",
		"extract": true,
		"color": "red"
	},
	"slack_token": {
		"loaded": true,
		"highlight": true,
		"regex": "(xox[p|b|o|a]-[0-9]{12}-[0-9]{12}-[0-9]{12}-[a-z0-9]{32})",
		"extract": true,
		"color": "red"
	},
	"azure_storage": {
		"loaded": true,
		"highlight": true,
		"regex": "(https?://[\\\\w-\\.]\\\\.file.core.windows.net)",
		"extract": true,
		"color": "red"
	},
	"aliyun_oss_url": {
		"loaded": true,
		"highlight": true,
		"regex": "([\\\\w-.]\\\\.oss.aliyuncs.com)",
		"extract": true,
		"color": "red"
	},
	"Ipone": {
		"loaded": true,
		"highlight": true,
		"regex": "([^0-9]+(1[3-9]\\d{9})[^0-9]+)",
		"extract": true,
		"color": "red"
	},
	"New Rule": {
		"loaded": true,
		"highlight": true,
		"regex": "([A|a]ccess[K|k]ey[I|i]d|[A|a]ccess[K|k]ey[S|s]ecret)",
		"extract": true,
		"color": "red"
	},
	"access_key": {
		"loaded": true,
		"highlight": true,
		"regex": "([Aa](ccess|CCESS)_?[Kk](ey|EY)|[Aa](ccess|CCESS)_?[sS](ecret|ECRET)|[Aa](ccess|CCESS)_?(id|ID|Id))",
		"extract": true,
		"color": "red"
	},
	"email": {
		"loaded": true,
		"highlight": true,
		"regex": "([\\w-]+(?:\\.[\\w-]+)*@(?:[\\w](?:[\\w-]*[\\w])?\\.)+[\\w](?:[\\w-]*[\\w])?)",
		"extract": true,
		"color": "red"
	}
}

**Comment by gh0stkey** [comment]
配置本身存在问题，修复后：
```regex
{"secret_key":{"loaded":true,"highlight":true,"regex":"(Ss?Kk)","extract":true,"color":"red"},"shior":{"loaded":true,"highlight":true,"regex":"(rememberMe=delete)","extract":true,"color":"red"},"slack_token":{"loaded":true,"highlight":true,"regex":"(xox[p|b|o|a]-[0-9]{12}-[0-9]{12}-[0-9]{12}-[a-z0-9]{32})","extract":true,"color":"red"},"azure_storage":{"loaded":true,"highlight":true,"regex":"(https?://[\\w-\\.]\\.file.core.windows.net)","extract":true,"color":"red"},"aliyun_oss_url":{"loaded":true,"highlight":true,"regex":"([\\w-.]\\.oss.aliyuncs.com)","extract":true,"color":"red"},"Ipone":{"loaded":true,"highlight":true,"regex":"([^0-9]+(1[3-9]\\d{9})[^0-9]+)","extract":true,"color":"red"},"New Rule":{"loaded":true,"highlight":true,"regex":"([A|a]ccess[K|k]ey[I|i]d|[A|a]ccess[K|k]ey[S|s]ecret)","extract":true,"color":"red"},"access_key":{"loaded":true,"highlight":true,"regex":"(Aa?Kk|Aa?sS|Aa?(id|ID|Id))","extract":true,"color":"red"},"email":{"loaded":true,"highlight":true,"regex":"([\\w-]+(?:\\.[\\w-]+)*@(?:\\w?\\.)+\\w?)","extract":true,"color":"red"}}
```
感谢提交！
