### ISSUE TITLE
有没有考虑加个注释功能

### ISSUE THREAD

**Issue by LztCode** [gh0stkey/HaE#53]
1、类似这个
![image](https://user-images.githubusercontent.com/73683679/160365409-97dc2786-f088-4e8b-95f9-b37f8f8aa4a6.png)
2、原因：色弱、颜色难以分辨

**Comment by gh0stkey** [comment]
该功能在HaE 2.1版本中已经添加：https://github.com/gh0stkey/HaE/releases/tag/2.1
