### ISSUE TITLE
希望能添加url或body中匹配editor的规则。

### ISSUE THREAD

**Issue by xslzlccc** [gh0stkey/HaE#55]
希望能添加url或body中匹配editor的规则。

**Comment by gh0stkey** [comment]
editor是指什么？

**Comment by xslzlccc** [comment]
> 麻烦看见回复一下哦

编辑器呀，fckeditor、ueditor、各种编辑器之类的，我自己写了条规则，直接匹配（editor）试了下还可以，但正则大佬估计有更好的规则（这条信息我昨天已经用qq邮箱回复过，不知道为什么github没显示）。

**Comment by gh0stkey** [comment]
好的，感谢建议，后期会去看看如何去适配该需求。
