### ISSUE TITLE
2022.3.2版本的burp加载报错

### ISSUE THREAD

**Issue by ziping21** [gh0stkey/HaE#57]
师傅好，2022.3.2版本的burp加载报错，插件所在路径是英文，排除中文路径问题，这个需要怎么解决
![图片](https://user-images.githubusercontent.com/63443757/163322777-e64986fc-9919-44e7-bc17-18f9d4f3536a.png)

**Comment by gh0stkey** [comment]
你仔细看看你的配置文件信息，不仅仅是路径，配置的内容也检查一下。
