### ISSUE TITLE
How to Save Output in MarkInfo tab to a file ???

### ISSUE THREAD

**Issue by samosa404** [gh0stkey/HaE#6]
名称：

介绍：

正则：

Firstly great tool , but is there a way to save all extracted data in markinfo tab to a file directly ??

**Comment by gh0stkey** [comment]
Now, it can't.Maybe u can copy then paste.

**Comment by samosa404** [comment]
uhh because i have 10000's of requests in it , so i can't possibly manually copy all of the result . 

But in extender tab of burp , this extension's output options , it has options like 
1) Output to system console
2) save to file
3) show in Ui 

but when i select a file in "save to file" option , it doesn't output anything  . 


Is there any other way to do it , or am i doing this the wrong way ?

**Comment by gh0stkey** [comment]
It's not supported for the time being, unless more people have the same needs, thanks!
