### ISSUE TITLE
用于匹配js中uri的正则，当碰到数据量较大的js时会将burp卡死

### ISSUE THREAD

**Issue by Ymigmli** [gh0stkey/HaE#60]
burp版本v2021.9
hae版本2.2

禁用掉这条正则就不会发生问题

(?:"|')
(?!\S+(?:\.jpe?g"|\.png"|\.bmp"|\.gif"|\.ttf"|\.woff2?"|\.ico"|\.svg"|\.ts"|\.css"|/css"|\.html"|/javascript"|/x-icon"|/\*"))
(((?:\w{1,10}(:|%3a)//|/|\.\./|\./)([^"'\n]){1,})|(?:[a-zA-Z0-9]+/([^"'\n]){1,}))
(?:"|')

正则说明：
从单双引号开始/结束匹配
不匹配后缀为jpe?g等内容
匹配xxx://xxx、/xxx、../xxx、./xxx和xxx/xxx的内容

匹配效果挺好用的，就是碰到数据量较大的js时会将burp卡死，很是头疼

请问这条正则可以优化吗？或者有相同效果但不会将burp卡死的正则可以共享下吗？或者是hae的问题？

因为burp并不会针对js中的链接进行拼接访问并放置到target中，且js中有很多敏感信息泄露有助于渗透测试

感谢

**Comment by gh0stkey** [comment]
这个实际上是Java的问题，在GUI加载过大的数据会导致卡死，目前还没有比较好的优化方案，BurpSuite和HaE都在努力优化中。
