### ISSUE TITLE
匹配出来的接口无法批量复制

### ISSUE THREAD

**Issue by 1979139113** [gh0stkey/HaE#61]
您好，现在匹配出来的数据是一个表格的形式，选择多条数据后，直接ctrl+c复制的是整个js文件内容，无法像之前那样只复制整个匹配出来的接口列表

**Comment by gh0stkey** [comment]
是的，我们也发现了，这个问题正在解决。

**Comment by gh0stkey** [comment]
该问题已经解决，请移步最新版本（2.2.1）下载。
https://github.com/gh0stkey/HaE/releases/tag/2.2.1

**Comment by gh0stkey** [comment]
记得Star项目哦～

**Comment by 1979139113** [comment]
已star，感谢
