### ISSUE TITLE
新版burp存在bug

### ISSUE THREAD

**Issue by lucksec** [gh0stkey/HaE#66]
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/59011386/173497469-b5d72c51-281d-4dee-9b87-d4723cb8f9be.png">
新版导入插件后报错

**Comment by gh0stkey** [comment]
替换下规则文件为最新的官方规则。

**Comment by Am-ev** [comment]
> 替换下规则文件为最新的官方规则。

哈喽大佬，jdk16 bp2021.10，启动参数java -Xmx8G -XX:-UseParallelGC --illegal-access=permit ，引入HAE插件后，浏览着浏览着bp就卡死无响应了。没有抓取到错误信息

**Comment by gh0stkey** [comment]
建议使用最新版本Burp，卡死可能是由于Java GUI无法承受这大量的数据导致界面加载异常。

**Comment by lucksec** [comment]
解决
