### ISSUE TITLE
建议增加Scope多选的功能

### ISSUE THREAD

**Issue by Lu0cky** [gh0stkey/HaE#67]
比如在一条规则中可以同时选择scope为 "request Body" 和"response Body "等多个scope

<img width="419" alt="image" src="https://user-images.githubusercontent.com/55577265/174732268-7dbd84ce-7f00-4b67-865f-51d8711aa332.png">

而且这里scope可以参照Burp的"Match and Replace"中的Type类型增加 "Request First Line"

<img width="612" alt="image" src="https://user-images.githubusercontent.com/55577265/174732666-2f2f177d-ce04-46ac-a0b0-c2ca96292f85.png">

**Comment by gh0stkey** [comment]
可以举例说明下场景吗，谢谢，目前来看HaE的作用域应该是够用的。

**Comment by Lu0cky** [comment]
> 

比如说我想匹配请求传参中的某个key(可能位于url或者body中)，但是这个key同时会出现在cookie或者referer(需要屏蔽)，如果scope选择了request，这样所有的流量都会匹配上，所以提了一个scope为url和规则支持多选范围的需求

**Comment by gh0stkey** [comment]
收到，通过你的举例，确实是有这个必要的，我们加入TODO List中，后期版本更新中有会所体现，感谢。
