### ISSUE TITLE
希望加上select file的功能!

### ISSUE THREAD

**Issue by ba1ma0** [gh0stkey/HaE#74]
版本:2.4.1-J9 (截至目前是最新版)

问题描述:最新版没有了select file(加载配置文件的功能),使用起来有一点点的不方便!使用起来只能将配置文件放到指定的文件夹下且改成Config.yml的格式才能使用之前的规则!

问题截图:
2.4.1-J9版本的HaE
<img width="1920" alt="截屏2022-07-11 16 46 07" src="https://user-images.githubusercontent.com/32502627/178225053-8c089c82-86a8-44fe-b8c1-2269e2671c50.png">
2.3-J9版本的HaE,有select file 功能
![截屏2022-07-11 16 47 09](https://user-images.githubusercontent.com/32502627/178225239-4c5d162b-b45a-4374-a1a3-c9e34d8cd4af.png)

**Comment by gh0stkey** [comment]
移除这个功能是为了治理配置文件路径乱放的现象，之前许多的issue都是因为自定义配置文件路径导致加载出错，所以现在固定了路径，暂时不考虑恢复该功能，但是我会将该建议放在项目后期开发中考虑，如果开发组讨论认为该功能确有必要，后期会重新添加上，感谢建议！
