### ISSUE TITLE
能否适配高版本java

### ISSUE THREAD

**Issue by WasteMaterial** [gh0stkey/HaE#75]
如题 
有幸体验过HaE在burp上获得的大量敏感信息，可是目前好像并不是配高版本java，
本人使用java17 如果有适配方法请回复，感谢。

**Comment by gh0stkey** [comment]
J9版本应该支持的

**Comment by WasteMaterial** [comment]
感谢   J9版本 已经正常使用在java17上了    应该是配置文件的问题才导致每次安装一直报错哈哈哈
