### ISSUE TITLE
当添加password正则时插件报错

### ISSUE THREAD

**Issue by TD0U** [gh0stkey/HaE#76]
((|'|")(pass|pwd|passwd|password)(|'|"):( |)(|'|")(.*?)(|'|"),)  我添加了如下正则导致插件报错
![image](https://user-images.githubusercontent.com/75050574/186583806-140230fa-235a-4cbd-b49a-e0e673852921.png)
![image](https://user-images.githubusercontent.com/75050574/186583940-f220fcd6-a68c-4344-b470-0f49eda43942.png)

**Comment by gh0stkey** [comment]
正则应是：`((|'|")([p](ass|wd|asswd|assword))(|'|")(:|=)( |)('|")(.*?)('|")(|,))`，你写的少了个括号。
