### ISSUE TITLE
linkfinder的规则在这个插件使用要怎么修改？

### ISSUE THREAD

**Issue by maybe-why-not** [gh0stkey/HaE#8]
首先在twitter看到这张图
![image](https://user-images.githubusercontent.com/29968903/98205353-f14cb100-1f72-11eb-9e2a-765e4a0fef15.png)
把regx复制过来
(?:"|')(((?:[a-zA-Z]{1,10}://|//)[^"'/]{1,}\.[a-zA-Z]{2,}[^"']{0,})|((?:/|\.\./|\./)[^"'><,;|[^"'><,;|()]{1,})|([a-zA-Z0-9_\-/]{1,}/[a-zA-Z0-9_\-/]{1,}\.(?:[a-zA-Z]{1,4}|action)(?:[\?|/][^"|']{0,}|))|([a-zA-Z0-9_\-]{1,}\.(?:php|asp|aspx|jsp|json|action|html|js|txt|xml)(?:\?[^"|']{0,}|)))(?:"|')
![image](https://user-images.githubusercontent.com/29968903/98205424-1b05d800-1f73-11eb-9cc4-ba63ba7d2956.png)
先证明regx是对的
![image](https://user-images.githubusercontent.com/29968903/98207354-82715700-1f76-11eb-8fcb-43c64f236615.png)
然后hae不工作了，也没有报错
![image](https://user-images.githubusercontent.com/29968903/98205563-56a0a200-1f73-11eb-8976-6bd0e15630d8.png)
不添加这条rule之前是能工作的
![image](https://user-images.githubusercontent.com/29968903/98205693-88196d80-1f73-11eb-8e68-6c2f8cf64975.png)
(?:"|')(......)(?:"|')这样的规则都是不行的

**Comment by gh0stkey** [comment]
我这里是可以正常工作的，正则：

```regex
(?:"|')(((?:[a-zA-Z]{1,10}://|//)[^"'/]{1,}\.[a-zA-Z]{2,}[^"']{0,})|((?:/|\.\./|\./)[^"'><,;|*()(%%$^/\\\[\]][^"'><,;|()]{1,})|([a-zA-Z0-9_\-/]{1,}/[a-zA-Z0-9_\-/]{1,}\.(?:[a-zA-Z]{1,4}|action)(?:[\?|#][^"|']{0,}|))|([a-zA-Z0-9_\-/]{1,}/[a-zA-Z0-9_\-/]{3,}(?:[\?|#][^"|']{0,}|))|([a-zA-Z0-9_\-]{1,}\.(?:php|asp|aspx|jsp|json|action|html|js|txt|xml|do|jspx|htm)(?:[\?|#][^"|']{0,}|)))(?:"|')
```

你可以尝试到Extender - Extensions - HaE - Errors 查看是否有报错信息，并贴出来，便于我查看，谢谢～

**Comment by maybe-why-not** [comment]
[^"'><,;| *()(%%$^/\\\[\]]          # Next character can't be...

**Comment by maybe-why-not** [comment]
[^"'><,;| *()(%%$^/\\\[\]]          # Next character can't be...
这一段有个空格，我删的时候" +.*?$"，后面被误删了一部分
