### ISSUE TITLE
java11加载插件报错

### ISSUE THREAD

**Issue by james99169** [gh0stkey/HaE#80]
java.lang.Exception: Extension class is not a recognized type	at burp.s4i.w(Unknown Source)	at burp.s4i.<init>(Unknown Source)	at burp.hwe.u(Unknown Source)	at burp.ir.lambda$panelLoaded$0(Unknown Source)	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by gh0stkey** [comment]
请使用J9版本加载。
