### ISSUE TITLE
hae正则匹配问题

### ISSUE THREAD

**Issue by zilyl** [gh0stkey/HaE#81]
![image](https://user-images.githubusercontent.com/40203396/190958524-3de266c5-63e9-42be-9826-3b2458b04e91.png)
为什么不带value的能按照关键词检测出来，带了value就不行了？

**Comment by gh0stkey** [comment]
正则内容麻烦贴一下呢

**Comment by zilyl** [comment]
> 正则内容麻烦贴一下呢

((q=)|(s=)|(search=)|(id=)|(lang=)|(keyword=)|(query=)|(page=)|(keywords=)|(year=)|(view=)|(email=)|(type=)|(name=)|(p=)|(month=)|(immagine=)|(list_type=)|(url=)|(terms=)|(categoryid=)|(key=)|(l=)|(begindate=)|(enddate=)|(message=)|(user=)|(type_name=)|(status=))

**Comment by gh0stkey** [comment]
我这边测试没问题呢，可以使用DFA引擎～

**Comment by zilyl** [comment]
换了低版本的burp正常了。
