### ISSUE TITLE
comment 小bug

### ISSUE THREAD

**Issue by k-fire** [gh0stkey/HaE#82]
更新burp版本至2022.9.1，comment 一点异常显示，首位多了一个逗号
![image](https://user-images.githubusercontent.com/40354487/191041126-db8c2205-f929-4a0e-adab-0f23b115cc47.png)

**Comment by gh0stkey** [comment]
感谢提交BUG，该问题前不久已经修复，忘记更新了，马上安排～

**Comment by gh0stkey** [comment]
已发布：https://github.com/gh0stkey/HaE/releases/tag/2.4.3
