### ISSUE TITLE
能否针对 Yakit 出一个插件

### ISSUE THREAD

**Issue by Asura88** [gh0stkey/HaE#83]
能否针对 Yakit 出一个插件

https://github.com/yaklang/yakit

**Comment by gh0stkey** [comment]
Yakit已经有类似HaE的功能了，可以看公众号文章：https://mp.weixin.qq.com/s/AAj36z1Oxn99viwrUAoD2A，所以暂时没有计划针对Yakit再出一个插件，感谢，顺便预告一下未来HaE将不仅限于BurpSuite，敬请期待。
