### ISSUE TITLE
功能建议: 添加匹配的信息全部展示功能，而不是以域名为划分

### ISSUE THREAD

**Issue by sv3nbeast** [gh0stkey/HaE#88]
有的时候域名有多个，单个搜索hae效率低

**Comment by gh0stkey** [comment]
这个功能的难点在于，如果根据匹配内容字段展示信息会有很多其他域名的数据，不便于观察和使用提取的数据，我们会在下一个版本中考虑是否加入类似的功能，感谢建议～
