### ISSUE TITLE
BurpSuite2020.11 显示问题

### ISSUE THREAD

**Issue by xuing** [gh0stkey/HaE#9]
名称：BurpSuite2020.11 显示问题

介绍：Response部分，无法正常显示MarkInfo信息了~~可能需要更新适配一下了。

![image](https://user-images.githubusercontent.com/11143269/98636203-592f3d00-2361-11eb-8957-690aac6484fd.png)

**Comment by gh0stkey** [comment]
这个是BurpSuite官方的BUG，与插件无关，请升级BurpSuite到最新版本使用～
