### ISSUE TITLE
插件有报错

### ISSUE THREAD

**Issue by Oddluo** [gh0stkey/HaE#90]
您好，这边遇到插件有报错 BURP版本2021.10.1，java环境 openjdk11，插件版本2.4.4，报错如下
![图片](https://user-images.githubusercontent.com/67694128/206911536-7a6d649c-6c92-48cb-9ffd-06d2c98e0fea.png)

**Comment by gh0stkey** [comment]
这个报错可以看一下以往的一些issue，都是配置文件导致的，建议删除配置文件，然后使用Online Update按钮进行更新配置文件
