### ISSUE TITLE
建议变更配置文件更新地址

### ISSUE THREAD

**Issue by k-fire** [gh0stkey/HaE#93]
建议使用 https://cdn.jsdelivr.net/gh/gh0stkey/HaE@gh-pages/Config.yml
不然更新时会由于网络报错：
![image](https://user-images.githubusercontent.com/40354487/209751588-af499200-d077-487b-b4f8-eed367b8a035.png)

**Comment by gh0stkey** [comment]
是个好建议，下个版本一并更新，感谢。
