### ISSUE TITLE
HAE优化建议

### ISSUE THREAD

**Issue by HToTH** [gh0stkey/HaE#96]
1.建议增加排除功能，比如排除jquery、google-analyst。
2.建议可以自己选择匹配的burpsuite模块，比如只在proxy里进行匹配，intruder、logger等模块不进行匹配。
3.插件的在线更新，好像没有走burp设置的代理。

**Comment by gh0stkey** [comment]
第一个排除功能暂时没想到比较好的方法去排除，我们后续再想想办法去除一些干扰；
第二个的功能确实是个不错的建议，我们后续会在新版本中去具体更新；
第三个插件的在线更新功能我们也考虑过了，走Burp的API会出错，跟官方也对接过所以暂时只能使用CDN得方式来缓解。

最后，感谢建议，谢谢您的使用～
